//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArchiveEntities : DbContext
    {
        public ArchiveEntities()
            : base("name=ArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblArchiveTreeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArchiveTreeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblArchiveTreeInsert(ObjectParameter fldID, Nullable<int> fldPID, string fldTitle, Nullable<bool> fldFileUpload, Nullable<int> fldOrganId, Nullable<int> fldModuleId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldPIDParameter = fldPID.HasValue ?
                new ObjectParameter("fldPID", fldPID) :
                new ObjectParameter("fldPID", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldFileUploadParameter = fldFileUpload.HasValue ?
                new ObjectParameter("fldFileUpload", fldFileUpload) :
                new ObjectParameter("fldFileUpload", typeof(bool));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldModuleIdParameter = fldModuleId.HasValue ?
                new ObjectParameter("fldModuleId", fldModuleId) :
                new ObjectParameter("fldModuleId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArchiveTreeInsert", fldID, fldPIDParameter, fldTitleParameter, fldFileUploadParameter, fldOrganIdParameter, fldModuleIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblArchiveTreeSelect> spr_tblArchiveTreeSelect(string fieldname, string value, Nullable<int> organId, string value2, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("value2", value2) :
                new ObjectParameter("value2", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblArchiveTreeSelect>("spr_tblArchiveTreeSelect", fieldnameParameter, valueParameter, organIdParameter, value2Parameter, hParameter);
        }
    
        public virtual int spr_tblArchiveTreeUpdate(Nullable<int> fldId, Nullable<int> fldPID, string fldTitle, Nullable<bool> fldFileUpload, Nullable<int> fldOrganId, Nullable<int> fldModuleId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldPIDParameter = fldPID.HasValue ?
                new ObjectParameter("fldPID", fldPID) :
                new ObjectParameter("fldPID", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldFileUploadParameter = fldFileUpload.HasValue ?
                new ObjectParameter("fldFileUpload", fldFileUpload) :
                new ObjectParameter("fldFileUpload", typeof(bool));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldModuleIdParameter = fldModuleId.HasValue ?
                new ObjectParameter("fldModuleId", fldModuleId) :
                new ObjectParameter("fldModuleId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArchiveTreeUpdate", fldIdParameter, fldPIDParameter, fldTitleParameter, fldFileUploadParameter, fldOrganIdParameter, fldModuleIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblFileMojazDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFileMojazDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblFileMojazInsert(Nullable<int> fldArchiveTreeId, Nullable<int> fldFormatFileId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldArchiveTreeIdParameter = fldArchiveTreeId.HasValue ?
                new ObjectParameter("fldArchiveTreeId", fldArchiveTreeId) :
                new ObjectParameter("fldArchiveTreeId", typeof(int));
    
            var fldFormatFileIdParameter = fldFormatFileId.HasValue ?
                new ObjectParameter("fldFormatFileId", fldFormatFileId) :
                new ObjectParameter("fldFormatFileId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFileMojazInsert", fldArchiveTreeIdParameter, fldFormatFileIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblFileMojazSelect> spr_tblFileMojazSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblFileMojazSelect>("spr_tblFileMojazSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblFileMojazUpdate(Nullable<int> fldId, Nullable<int> fldArchiveTreeId, Nullable<int> fldFormatFileId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldArchiveTreeIdParameter = fldArchiveTreeId.HasValue ?
                new ObjectParameter("fldArchiveTreeId", fldArchiveTreeId) :
                new ObjectParameter("fldArchiveTreeId", typeof(int));
    
            var fldFormatFileIdParameter = fldFormatFileId.HasValue ?
                new ObjectParameter("fldFormatFileId", fldFormatFileId) :
                new ObjectParameter("fldFormatFileId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFileMojazUpdate", fldIdParameter, fldArchiveTreeIdParameter, fldFormatFileIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblParticularPropertiesDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParticularPropertiesDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblParticularPropertiesInsert(Nullable<int> fldArchiveTreeId, Nullable<int> fldPropertiesId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldArchiveTreeIdParameter = fldArchiveTreeId.HasValue ?
                new ObjectParameter("fldArchiveTreeId", fldArchiveTreeId) :
                new ObjectParameter("fldArchiveTreeId", typeof(int));
    
            var fldPropertiesIdParameter = fldPropertiesId.HasValue ?
                new ObjectParameter("fldPropertiesId", fldPropertiesId) :
                new ObjectParameter("fldPropertiesId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParticularPropertiesInsert", fldArchiveTreeIdParameter, fldPropertiesIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblParticularPropertiesSelect> spr_tblParticularPropertiesSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblParticularPropertiesSelect>("spr_tblParticularPropertiesSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblParticularPropertiesUpdate(Nullable<int> fldId, Nullable<int> fldArchiveTreeId, Nullable<int> fldPropertiesId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldArchiveTreeIdParameter = fldArchiveTreeId.HasValue ?
                new ObjectParameter("fldArchiveTreeId", fldArchiveTreeId) :
                new ObjectParameter("fldArchiveTreeId", typeof(int));
    
            var fldPropertiesIdParameter = fldPropertiesId.HasValue ?
                new ObjectParameter("fldPropertiesId", fldPropertiesId) :
                new ObjectParameter("fldPropertiesId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParticularPropertiesUpdate", fldIdParameter, fldArchiveTreeIdParameter, fldPropertiesIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblPropertiesDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblPropertiesInsert(string fldNameFn, string fldNameEn, Nullable<int> fldType, Nullable<int> fldFormulId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldNameFnParameter = fldNameFn != null ?
                new ObjectParameter("fldNameFn", fldNameFn) :
                new ObjectParameter("fldNameFn", typeof(string));
    
            var fldNameEnParameter = fldNameEn != null ?
                new ObjectParameter("fldNameEn", fldNameEn) :
                new ObjectParameter("fldNameEn", typeof(string));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(int));
    
            var fldFormulIdParameter = fldFormulId.HasValue ?
                new ObjectParameter("fldFormulId", fldFormulId) :
                new ObjectParameter("fldFormulId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesInsert", fldNameFnParameter, fldNameEnParameter, fldTypeParameter, fldFormulIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblPropertiesSelect> spr_tblPropertiesSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblPropertiesSelect>("spr_tblPropertiesSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblPropertiesUpdate(Nullable<int> fldId, string fldNameFn, string fldNameEn, Nullable<int> fldType, Nullable<int> fldFormulId, Nullable<int> fldUserId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldNameFnParameter = fldNameFn != null ?
                new ObjectParameter("fldNameFn", fldNameFn) :
                new ObjectParameter("fldNameFn", typeof(string));
    
            var fldNameEnParameter = fldNameEn != null ?
                new ObjectParameter("fldNameEn", fldNameEn) :
                new ObjectParameter("fldNameEn", typeof(string));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(int));
    
            var fldFormulIdParameter = fldFormulId.HasValue ?
                new ObjectParameter("fldFormulId", fldFormulId) :
                new ObjectParameter("fldFormulId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesUpdate", fldIdParameter, fldNameFnParameter, fldNameEnParameter, fldTypeParameter, fldFormulIdParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblPropertiesValuesDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesValuesDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblPropertiesValuesInsert(Nullable<int> fldParticularId, string fldValue, Nullable<int> fldUserId, string fldDesc)
        {
            var fldParticularIdParameter = fldParticularId.HasValue ?
                new ObjectParameter("fldParticularId", fldParticularId) :
                new ObjectParameter("fldParticularId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesValuesInsert", fldParticularIdParameter, fldValueParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblPropertiesValuesSelect> spr_tblPropertiesValuesSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblPropertiesValuesSelect>("spr_tblPropertiesValuesSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblPropertiesValuesUpdate(Nullable<int> fldId, Nullable<int> fldParticularId, string fldValue, Nullable<int> fldUserId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldParticularIdParameter = fldParticularId.HasValue ?
                new ObjectParameter("fldParticularId", fldParticularId) :
                new ObjectParameter("fldParticularId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblPropertiesValuesUpdate", fldIdParameter, fldParticularIdParameter, fldValueParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_SelectArchiveTree_Module> spr_SelectArchiveTree_Module(Nullable<int> organId, Nullable<int> moduleId, string value)
        {
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectArchiveTree_Module>("spr_SelectArchiveTree_Module", organIdParameter, moduleIdParameter, valueParameter);
        }
    }
}
