//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChekEntities : DbContext
    {
        public ChekEntities()
            : base("name=ChekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblOlgoCheckDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblOlgoCheckDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblOlgoCheckInsert(byte[] fldFile, string fldPasvand, Nullable<int> fldIdBank, Nullable<int> fldUserID, string fldDesc, string fldTitle, Nullable<int> fldOrganId)
        {
            var fldFileParameter = fldFile != null ?
                new ObjectParameter("fldFile", fldFile) :
                new ObjectParameter("fldFile", typeof(byte[]));
    
            var fldPasvandParameter = fldPasvand != null ?
                new ObjectParameter("fldPasvand", fldPasvand) :
                new ObjectParameter("fldPasvand", typeof(string));
    
            var fldIdBankParameter = fldIdBank.HasValue ?
                new ObjectParameter("fldIdBank", fldIdBank) :
                new ObjectParameter("fldIdBank", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblOlgoCheckInsert", fldFileParameter, fldPasvandParameter, fldIdBankParameter, fldUserIDParameter, fldDescParameter, fldTitleParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblOlgoCheckUpdate(Nullable<int> fldId, byte[] fldFile, string fldPasvand, Nullable<int> fldIdFile, Nullable<int> fldIdBank, Nullable<int> fldUserID, string fldDesc, string fldTitle, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldFileParameter = fldFile != null ?
                new ObjectParameter("fldFile", fldFile) :
                new ObjectParameter("fldFile", typeof(byte[]));
    
            var fldPasvandParameter = fldPasvand != null ?
                new ObjectParameter("fldPasvand", fldPasvand) :
                new ObjectParameter("fldPasvand", typeof(string));
    
            var fldIdFileParameter = fldIdFile.HasValue ?
                new ObjectParameter("fldIdFile", fldIdFile) :
                new ObjectParameter("fldIdFile", typeof(int));
    
            var fldIdBankParameter = fldIdBank.HasValue ?
                new ObjectParameter("fldIdBank", fldIdBank) :
                new ObjectParameter("fldIdBank", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblOlgoCheckUpdate", fldIdParameter, fldFileParameter, fldPasvandParameter, fldIdFileParameter, fldIdBankParameter, fldUserIDParameter, fldDescParameter, fldTitleParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblDasteCheckDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblDasteCheckDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblDasteCheckInsert(Nullable<int> fldIdOlgoCheck, Nullable<int> fldShomareHesab, string fldMoshakhaseDasteCheck, Nullable<byte> fldTedadBarg, string fldShoroeSeriyal, Nullable<int> fldUserID, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldIdOlgoCheckParameter = fldIdOlgoCheck.HasValue ?
                new ObjectParameter("fldIdOlgoCheck", fldIdOlgoCheck) :
                new ObjectParameter("fldIdOlgoCheck", typeof(int));
    
            var fldShomareHesabParameter = fldShomareHesab.HasValue ?
                new ObjectParameter("fldShomareHesab", fldShomareHesab) :
                new ObjectParameter("fldShomareHesab", typeof(int));
    
            var fldMoshakhaseDasteCheckParameter = fldMoshakhaseDasteCheck != null ?
                new ObjectParameter("fldMoshakhaseDasteCheck", fldMoshakhaseDasteCheck) :
                new ObjectParameter("fldMoshakhaseDasteCheck", typeof(string));
    
            var fldTedadBargParameter = fldTedadBarg.HasValue ?
                new ObjectParameter("fldTedadBarg", fldTedadBarg) :
                new ObjectParameter("fldTedadBarg", typeof(byte));
    
            var fldShoroeSeriyalParameter = fldShoroeSeriyal != null ?
                new ObjectParameter("fldShoroeSeriyal", fldShoroeSeriyal) :
                new ObjectParameter("fldShoroeSeriyal", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblDasteCheckInsert", fldIdOlgoCheckParameter, fldShomareHesabParameter, fldMoshakhaseDasteCheckParameter, fldTedadBargParameter, fldShoroeSeriyalParameter, fldUserIDParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblDasteCheckUpdate(Nullable<int> fldId, Nullable<int> fldIdOlgoCheck, Nullable<int> fldShomareHesab, string fldMoshakhaseDasteCheck, Nullable<byte> fldTedadBarg, string fldShoroeSeriyal, Nullable<int> fldUserID, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldIdOlgoCheckParameter = fldIdOlgoCheck.HasValue ?
                new ObjectParameter("fldIdOlgoCheck", fldIdOlgoCheck) :
                new ObjectParameter("fldIdOlgoCheck", typeof(int));
    
            var fldShomareHesabParameter = fldShomareHesab.HasValue ?
                new ObjectParameter("fldShomareHesab", fldShomareHesab) :
                new ObjectParameter("fldShomareHesab", typeof(int));
    
            var fldMoshakhaseDasteCheckParameter = fldMoshakhaseDasteCheck != null ?
                new ObjectParameter("fldMoshakhaseDasteCheck", fldMoshakhaseDasteCheck) :
                new ObjectParameter("fldMoshakhaseDasteCheck", typeof(string));
    
            var fldTedadBargParameter = fldTedadBarg.HasValue ?
                new ObjectParameter("fldTedadBarg", fldTedadBarg) :
                new ObjectParameter("fldTedadBarg", typeof(byte));
    
            var fldShoroeSeriyalParameter = fldShoroeSeriyal != null ?
                new ObjectParameter("fldShoroeSeriyal", fldShoroeSeriyal) :
                new ObjectParameter("fldShoroeSeriyal", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblDasteCheckUpdate", fldIdParameter, fldIdOlgoCheckParameter, fldShomareHesabParameter, fldMoshakhaseDasteCheckParameter, fldTedadBargParameter, fldShoroeSeriyalParameter, fldUserIDParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblSodorCheckDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblSodorCheckDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblSodorCheckInsert(ObjectParameter fldID, Nullable<int> fldIdDasteCheck, string fldTarikhVosol, Nullable<int> fldAshkhasId, string fldCodeSerialCheck, string fldBabat, Nullable<bool> fldBabatFlag, Nullable<long> fldMablagh, Nullable<int> fldFactorId, Nullable<int> fldContractId, Nullable<int> fldTankhahGroupId, string fldDesc, Nullable<int> fldUserId, Nullable<int> fldOrganId)
        {
            var fldIdDasteCheckParameter = fldIdDasteCheck.HasValue ?
                new ObjectParameter("fldIdDasteCheck", fldIdDasteCheck) :
                new ObjectParameter("fldIdDasteCheck", typeof(int));
    
            var fldTarikhVosolParameter = fldTarikhVosol != null ?
                new ObjectParameter("fldTarikhVosol", fldTarikhVosol) :
                new ObjectParameter("fldTarikhVosol", typeof(string));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldCodeSerialCheckParameter = fldCodeSerialCheck != null ?
                new ObjectParameter("fldCodeSerialCheck", fldCodeSerialCheck) :
                new ObjectParameter("fldCodeSerialCheck", typeof(string));
    
            var fldBabatParameter = fldBabat != null ?
                new ObjectParameter("fldBabat", fldBabat) :
                new ObjectParameter("fldBabat", typeof(string));
    
            var fldBabatFlagParameter = fldBabatFlag.HasValue ?
                new ObjectParameter("fldBabatFlag", fldBabatFlag) :
                new ObjectParameter("fldBabatFlag", typeof(bool));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldFactorIdParameter = fldFactorId.HasValue ?
                new ObjectParameter("fldFactorId", fldFactorId) :
                new ObjectParameter("fldFactorId", typeof(int));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldTankhahGroupIdParameter = fldTankhahGroupId.HasValue ?
                new ObjectParameter("fldTankhahGroupId", fldTankhahGroupId) :
                new ObjectParameter("fldTankhahGroupId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblSodorCheckInsert", fldID, fldIdDasteCheckParameter, fldTarikhVosolParameter, fldAshkhasIdParameter, fldCodeSerialCheckParameter, fldBabatParameter, fldBabatFlagParameter, fldMablaghParameter, fldFactorIdParameter, fldContractIdParameter, fldTankhahGroupIdParameter, fldDescParameter, fldUserIdParameter, fldOrganIdParameter);
        }
    
        public virtual ObjectResult<spr_tblSodorCheckSelect> spr_tblSodorCheckSelect(string fieldname, string value, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblSodorCheckSelect>("spr_tblSodorCheckSelect", fieldnameParameter, valueParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual int spr_tblSodorCheckUpdate(Nullable<int> fldId, Nullable<int> fldIdDasteCheck, string fldTarikhVosol, Nullable<int> fldAshkhasId, string fldCodeSerialCheck, string fldBabat, Nullable<bool> fldBabatFlag, Nullable<long> fldMablagh, Nullable<int> fldFactorId, Nullable<int> fldContractId, Nullable<int> fldTankhahGroupId, string fldDesc, Nullable<int> fldUserId, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldIdDasteCheckParameter = fldIdDasteCheck.HasValue ?
                new ObjectParameter("fldIdDasteCheck", fldIdDasteCheck) :
                new ObjectParameter("fldIdDasteCheck", typeof(int));
    
            var fldTarikhVosolParameter = fldTarikhVosol != null ?
                new ObjectParameter("fldTarikhVosol", fldTarikhVosol) :
                new ObjectParameter("fldTarikhVosol", typeof(string));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldCodeSerialCheckParameter = fldCodeSerialCheck != null ?
                new ObjectParameter("fldCodeSerialCheck", fldCodeSerialCheck) :
                new ObjectParameter("fldCodeSerialCheck", typeof(string));
    
            var fldBabatParameter = fldBabat != null ?
                new ObjectParameter("fldBabat", fldBabat) :
                new ObjectParameter("fldBabat", typeof(string));
    
            var fldBabatFlagParameter = fldBabatFlag.HasValue ?
                new ObjectParameter("fldBabatFlag", fldBabatFlag) :
                new ObjectParameter("fldBabatFlag", typeof(bool));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldFactorIdParameter = fldFactorId.HasValue ?
                new ObjectParameter("fldFactorId", fldFactorId) :
                new ObjectParameter("fldFactorId", typeof(int));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldTankhahGroupIdParameter = fldTankhahGroupId.HasValue ?
                new ObjectParameter("fldTankhahGroupId", fldTankhahGroupId) :
                new ObjectParameter("fldTankhahGroupId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblSodorCheckUpdate", fldIdParameter, fldIdDasteCheckParameter, fldTarikhVosolParameter, fldAshkhasIdParameter, fldCodeSerialCheckParameter, fldBabatParameter, fldBabatFlagParameter, fldMablaghParameter, fldFactorIdParameter, fldContractIdParameter, fldTankhahGroupIdParameter, fldDescParameter, fldUserIdParameter, fldOrganIdParameter);
        }
    
        public virtual ObjectResult<spr_tblOlgoCheckSelect> spr_tblOlgoCheckSelect(string fieldname, string value, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblOlgoCheckSelect>("spr_tblOlgoCheckSelect", fieldnameParameter, valueParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblDasteCheckSelect> spr_tblDasteCheckSelect(string fieldname, string value, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblDasteCheckSelect>("spr_tblDasteCheckSelect", fieldnameParameter, valueParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual int spr_tblAghsatCheckAmaniDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAghsatCheckAmaniDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblAghsatCheckAmaniInsert(Nullable<long> fldMablagh, string fldTarikh, string fldNobat, Nullable<int> fldIdCheckHayeVarede, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldNobatParameter = fldNobat != null ?
                new ObjectParameter("fldNobat", fldNobat) :
                new ObjectParameter("fldNobat", typeof(string));
    
            var fldIdCheckHayeVaredeParameter = fldIdCheckHayeVarede.HasValue ?
                new ObjectParameter("fldIdCheckHayeVarede", fldIdCheckHayeVarede) :
                new ObjectParameter("fldIdCheckHayeVarede", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAghsatCheckAmaniInsert", fldMablaghParameter, fldTarikhParameter, fldNobatParameter, fldIdCheckHayeVaredeParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual ObjectResult<spr_tblAghsatCheckAmaniSelect> spr_tblAghsatCheckAmaniSelect(string fieldname, string value, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblAghsatCheckAmaniSelect>("spr_tblAghsatCheckAmaniSelect", fieldnameParameter, valueParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual int spr_tblAghsatCheckAmaniUpdate(Nullable<int> fldId, Nullable<long> fldMablagh, string fldTarikh, string fldNobat, Nullable<int> fldIdCheckHayeVarede, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldNobatParameter = fldNobat != null ?
                new ObjectParameter("fldNobat", fldNobat) :
                new ObjectParameter("fldNobat", typeof(string));
    
            var fldIdCheckHayeVaredeParameter = fldIdCheckHayeVarede.HasValue ?
                new ObjectParameter("fldIdCheckHayeVarede", fldIdCheckHayeVarede) :
                new ObjectParameter("fldIdCheckHayeVarede", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAghsatCheckAmaniUpdate", fldIdParameter, fldMablaghParameter, fldTarikhParameter, fldNobatParameter, fldIdCheckHayeVaredeParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblCheckHayeVaredeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheckHayeVaredeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblCheckHayeVaredeInsert(Nullable<int> fldIdShobe, Nullable<int> fldMablagh, Nullable<int> fldAshkhasId, string fldTarikhVosolCheck, string fldTarikhDaryaftCheck, string fldShenaseKamelCheck, string fldBabat, Nullable<bool> fldNoeeCheck, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldIdShobeParameter = fldIdShobe.HasValue ?
                new ObjectParameter("fldIdShobe", fldIdShobe) :
                new ObjectParameter("fldIdShobe", typeof(int));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(int));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldTarikhVosolCheckParameter = fldTarikhVosolCheck != null ?
                new ObjectParameter("fldTarikhVosolCheck", fldTarikhVosolCheck) :
                new ObjectParameter("fldTarikhVosolCheck", typeof(string));
    
            var fldTarikhDaryaftCheckParameter = fldTarikhDaryaftCheck != null ?
                new ObjectParameter("fldTarikhDaryaftCheck", fldTarikhDaryaftCheck) :
                new ObjectParameter("fldTarikhDaryaftCheck", typeof(string));
    
            var fldShenaseKamelCheckParameter = fldShenaseKamelCheck != null ?
                new ObjectParameter("fldShenaseKamelCheck", fldShenaseKamelCheck) :
                new ObjectParameter("fldShenaseKamelCheck", typeof(string));
    
            var fldBabatParameter = fldBabat != null ?
                new ObjectParameter("fldBabat", fldBabat) :
                new ObjectParameter("fldBabat", typeof(string));
    
            var fldNoeeCheckParameter = fldNoeeCheck.HasValue ?
                new ObjectParameter("fldNoeeCheck", fldNoeeCheck) :
                new ObjectParameter("fldNoeeCheck", typeof(bool));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheckHayeVaredeInsert", fldIdShobeParameter, fldMablaghParameter, fldAshkhasIdParameter, fldTarikhVosolCheckParameter, fldTarikhDaryaftCheckParameter, fldShenaseKamelCheckParameter, fldBabatParameter, fldNoeeCheckParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_tblCheckHayeVaredeUpdate(Nullable<int> fldId, Nullable<int> fldIdShobe, Nullable<int> fldMablagh, Nullable<int> fldAshkhasId, string fldTarikhVosolCheck, string fldTarikhDaryaftCheck, string fldShenaseKamelCheck, string fldBabat, Nullable<bool> fldNoeeCheck, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldIdShobeParameter = fldIdShobe.HasValue ?
                new ObjectParameter("fldIdShobe", fldIdShobe) :
                new ObjectParameter("fldIdShobe", typeof(int));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(int));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldTarikhVosolCheckParameter = fldTarikhVosolCheck != null ?
                new ObjectParameter("fldTarikhVosolCheck", fldTarikhVosolCheck) :
                new ObjectParameter("fldTarikhVosolCheck", typeof(string));
    
            var fldTarikhDaryaftCheckParameter = fldTarikhDaryaftCheck != null ?
                new ObjectParameter("fldTarikhDaryaftCheck", fldTarikhDaryaftCheck) :
                new ObjectParameter("fldTarikhDaryaftCheck", typeof(string));
    
            var fldShenaseKamelCheckParameter = fldShenaseKamelCheck != null ?
                new ObjectParameter("fldShenaseKamelCheck", fldShenaseKamelCheck) :
                new ObjectParameter("fldShenaseKamelCheck", typeof(string));
    
            var fldBabatParameter = fldBabat != null ?
                new ObjectParameter("fldBabat", fldBabat) :
                new ObjectParameter("fldBabat", typeof(string));
    
            var fldNoeeCheckParameter = fldNoeeCheck.HasValue ?
                new ObjectParameter("fldNoeeCheck", fldNoeeCheck) :
                new ObjectParameter("fldNoeeCheck", typeof(bool));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheckHayeVaredeUpdate", fldIdParameter, fldIdShobeParameter, fldMablaghParameter, fldAshkhasIdParameter, fldTarikhVosolCheckParameter, fldTarikhDaryaftCheckParameter, fldShenaseKamelCheckParameter, fldBabatParameter, fldNoeeCheckParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_UpdateStatusAghsatCheckAmani(Nullable<int> fldId, string fldTarikhPardakht, Nullable<byte> fldVaziat, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTarikhPardakhtParameter = fldTarikhPardakht != null ?
                new ObjectParameter("fldTarikhPardakht", fldTarikhPardakht) :
                new ObjectParameter("fldTarikhPardakht", typeof(string));
    
            var fldVaziatParameter = fldVaziat.HasValue ?
                new ObjectParameter("fldVaziat", fldVaziat) :
                new ObjectParameter("fldVaziat", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateStatusAghsatCheckAmani", fldIdParameter, fldTarikhPardakhtParameter, fldVaziatParameter, fldUserIdParameter);
        }
    
        public virtual int spr_AghsatCheckAmaniDelete_CheckHayeVaredeId(Nullable<int> checkHayeVaredeId, Nullable<int> fldUserID)
        {
            var checkHayeVaredeIdParameter = checkHayeVaredeId.HasValue ?
                new ObjectParameter("CheckHayeVaredeId", checkHayeVaredeId) :
                new ObjectParameter("CheckHayeVaredeId", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_AghsatCheckAmaniDelete_CheckHayeVaredeId", checkHayeVaredeIdParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblCheckStatusInsert(Nullable<int> fldSodorCheckId, Nullable<int> fldCheckVaredeId, Nullable<int> fldAghsatId, Nullable<byte> fldStatus, string fldTarikh, Nullable<int> fldUserId, string fldDesc)
        {
            var fldSodorCheckIdParameter = fldSodorCheckId.HasValue ?
                new ObjectParameter("fldSodorCheckId", fldSodorCheckId) :
                new ObjectParameter("fldSodorCheckId", typeof(int));
    
            var fldCheckVaredeIdParameter = fldCheckVaredeId.HasValue ?
                new ObjectParameter("fldCheckVaredeId", fldCheckVaredeId) :
                new ObjectParameter("fldCheckVaredeId", typeof(int));
    
            var fldAghsatIdParameter = fldAghsatId.HasValue ?
                new ObjectParameter("fldAghsatId", fldAghsatId) :
                new ObjectParameter("fldAghsatId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheckStatusInsert", fldSodorCheckIdParameter, fldCheckVaredeIdParameter, fldAghsatIdParameter, fldStatusParameter, fldTarikhParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblCheckStatusSelect> spr_tblCheckStatusSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblCheckStatusSelect>("spr_tblCheckStatusSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblCheckHayeVaredeSelect> spr_tblCheckHayeVaredeSelect(string fieldname, string value, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblCheckHayeVaredeSelect>("spr_tblCheckHayeVaredeSelect", fieldnameParameter, valueParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblCheck_FactorSelect> spr_tblCheck_FactorSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblCheck_FactorSelect>("spr_tblCheck_FactorSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_SelectSumCheckSadere> spr_SelectSumCheckSadere(string fieldname, string value)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectSumCheckSadere>("spr_SelectSumCheckSadere", fieldnameParameter, valueParameter);
        }
    }
}
