//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeceasedEntities : DbContext
    {
        public DeceasedEntities()
            : base("name=DeceasedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblCauseOfDeathDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCauseOfDeathDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblCauseOfDeathInsert(string fldReason, Nullable<int> fldUserID, string fldDesc, string fldIP)
        {
            var fldReasonParameter = fldReason != null ?
                new ObjectParameter("fldReason", fldReason) :
                new ObjectParameter("fldReason", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCauseOfDeathInsert", fldReasonParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblCauseOfDeathSelect> spr_tblCauseOfDeathSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblCauseOfDeathSelect>("spr_tblCauseOfDeathSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblCauseOfDeathUpdate(Nullable<int> fldId, string fldReason, Nullable<int> fldUserID, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldReasonParameter = fldReason != null ?
                new ObjectParameter("fldReason", fldReason) :
                new ObjectParameter("fldReason", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCauseOfDeathUpdate", fldIdParameter, fldReasonParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblVadiSalamDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblVadiSalamDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblVadiSalamInsert(string fldName, Nullable<int> fldStateId, Nullable<int> fldCityId, Nullable<int> fldOrganId, string fldAddress, string fldLatitude, string fldLongitude, Nullable<int> fldUserID, string fldDesc, string fldIP)
        {
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldStateIdParameter = fldStateId.HasValue ?
                new ObjectParameter("fldStateId", fldStateId) :
                new ObjectParameter("fldStateId", typeof(int));
    
            var fldCityIdParameter = fldCityId.HasValue ?
                new ObjectParameter("fldCityId", fldCityId) :
                new ObjectParameter("fldCityId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldLatitudeParameter = fldLatitude != null ?
                new ObjectParameter("fldLatitude", fldLatitude) :
                new ObjectParameter("fldLatitude", typeof(string));
    
            var fldLongitudeParameter = fldLongitude != null ?
                new ObjectParameter("fldLongitude", fldLongitude) :
                new ObjectParameter("fldLongitude", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblVadiSalamInsert", fldNameParameter, fldStateIdParameter, fldCityIdParameter, fldOrganIdParameter, fldAddressParameter, fldLatitudeParameter, fldLongitudeParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblVadiSalamSelect> spr_tblVadiSalamSelect(string fieldName, string value, Nullable<int> organid, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organidParameter = organid.HasValue ?
                new ObjectParameter("organid", organid) :
                new ObjectParameter("organid", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblVadiSalamSelect>("spr_tblVadiSalamSelect", fieldNameParameter, valueParameter, organidParameter, hParameter);
        }
    
        public virtual int spr_tblVadiSalamUpdate(Nullable<int> fldId, string fldName, Nullable<int> fldStateId, Nullable<int> fldCityId, Nullable<int> fldOrganId, string fldAddress, string fldLatitude, string fldLongitude, Nullable<int> fldUserID, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldStateIdParameter = fldStateId.HasValue ?
                new ObjectParameter("fldStateId", fldStateId) :
                new ObjectParameter("fldStateId", typeof(int));
    
            var fldCityIdParameter = fldCityId.HasValue ?
                new ObjectParameter("fldCityId", fldCityId) :
                new ObjectParameter("fldCityId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldLatitudeParameter = fldLatitude != null ?
                new ObjectParameter("fldLatitude", fldLatitude) :
                new ObjectParameter("fldLatitude", typeof(string));
    
            var fldLongitudeParameter = fldLongitude != null ?
                new ObjectParameter("fldLongitude", fldLongitude) :
                new ObjectParameter("fldLongitude", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblVadiSalamUpdate", fldIdParameter, fldNameParameter, fldStateIdParameter, fldCityIdParameter, fldOrganIdParameter, fldAddressParameter, fldLatitudeParameter, fldLongitudeParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblGheteDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGheteDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblGheteInsert(Nullable<int> fldVadiSalamId, string fldNameGhete, Nullable<int> fldOrganid, Nullable<int> fldUserId, string fldIP, string fldDesc, Nullable<int> fldRadif, Nullable<int> fldShomare, string fldTabaghe)
        {
            var fldVadiSalamIdParameter = fldVadiSalamId.HasValue ?
                new ObjectParameter("fldVadiSalamId", fldVadiSalamId) :
                new ObjectParameter("fldVadiSalamId", typeof(int));
    
            var fldNameGheteParameter = fldNameGhete != null ?
                new ObjectParameter("fldNameGhete", fldNameGhete) :
                new ObjectParameter("fldNameGhete", typeof(string));
    
            var fldOrganidParameter = fldOrganid.HasValue ?
                new ObjectParameter("fldOrganid", fldOrganid) :
                new ObjectParameter("fldOrganid", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldRadifParameter = fldRadif.HasValue ?
                new ObjectParameter("fldRadif", fldRadif) :
                new ObjectParameter("fldRadif", typeof(int));
    
            var fldShomareParameter = fldShomare.HasValue ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(int));
    
            var fldTabagheParameter = fldTabaghe != null ?
                new ObjectParameter("fldTabaghe", fldTabaghe) :
                new ObjectParameter("fldTabaghe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGheteInsert", fldVadiSalamIdParameter, fldNameGheteParameter, fldOrganidParameter, fldUserIdParameter, fldIPParameter, fldDescParameter, fldRadifParameter, fldShomareParameter, fldTabagheParameter);
        }
    
        public virtual ObjectResult<spr_tblGheteSelect> spr_tblGheteSelect(string fieldName, string value, Nullable<int> id, Nullable<int> organid, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var organidParameter = organid.HasValue ?
                new ObjectParameter("organid", organid) :
                new ObjectParameter("organid", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblGheteSelect>("spr_tblGheteSelect", fieldNameParameter, valueParameter, idParameter, organidParameter, hParameter);
        }
    
        public virtual int spr_tblGheteUpdate(Nullable<int> fldId, Nullable<int> fldVadiSalamId, string fldNameGhete, Nullable<int> fldorganid, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldVadiSalamIdParameter = fldVadiSalamId.HasValue ?
                new ObjectParameter("fldVadiSalamId", fldVadiSalamId) :
                new ObjectParameter("fldVadiSalamId", typeof(int));
    
            var fldNameGheteParameter = fldNameGhete != null ?
                new ObjectParameter("fldNameGhete", fldNameGhete) :
                new ObjectParameter("fldNameGhete", typeof(string));
    
            var fldorganidParameter = fldorganid.HasValue ?
                new ObjectParameter("fldorganid", fldorganid) :
                new ObjectParameter("fldorganid", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGheteUpdate", fldIdParameter, fldVadiSalamIdParameter, fldNameGheteParameter, fldorganidParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblRadifDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRadifDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblRadifInsert(Nullable<int> fldGheteId, string fldNameRadif, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldGheteIdParameter = fldGheteId.HasValue ?
                new ObjectParameter("fldGheteId", fldGheteId) :
                new ObjectParameter("fldGheteId", typeof(int));
    
            var fldNameRadifParameter = fldNameRadif != null ?
                new ObjectParameter("fldNameRadif", fldNameRadif) :
                new ObjectParameter("fldNameRadif", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRadifInsert", fldGheteIdParameter, fldNameRadifParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblRadifSelect> spr_tblRadifSelect(string fieldName, string value, Nullable<int> id, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblRadifSelect>("spr_tblRadifSelect", fieldNameParameter, valueParameter, idParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual int spr_tblRadifUpdate(Nullable<int> fldId, Nullable<int> fldGheteId, string fldNameRadif, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldGheteIdParameter = fldGheteId.HasValue ?
                new ObjectParameter("fldGheteId", fldGheteId) :
                new ObjectParameter("fldGheteId", typeof(int));
    
            var fldNameRadifParameter = fldNameRadif != null ?
                new ObjectParameter("fldNameRadif", fldNameRadif) :
                new ObjectParameter("fldNameRadif", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRadifUpdate", fldIdParameter, fldGheteIdParameter, fldNameRadifParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblShomareDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblShomareDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblShomareInsert(Nullable<int> fldRadifId, string fldShomare, Nullable<byte> fldTedadTabaghat, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIp, string fldDesc)
        {
            var fldRadifIdParameter = fldRadifId.HasValue ?
                new ObjectParameter("fldRadifId", fldRadifId) :
                new ObjectParameter("fldRadifId", typeof(int));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldTedadTabaghatParameter = fldTedadTabaghat.HasValue ?
                new ObjectParameter("fldTedadTabaghat", fldTedadTabaghat) :
                new ObjectParameter("fldTedadTabaghat", typeof(byte));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIpParameter = fldIp != null ?
                new ObjectParameter("fldIp", fldIp) :
                new ObjectParameter("fldIp", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblShomareInsert", fldRadifIdParameter, fldShomareParameter, fldTedadTabaghatParameter, fldOrganIdParameter, fldUserIdParameter, fldIpParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblShomareSelect> spr_tblShomareSelect(string fieldName, string value, Nullable<int> id, Nullable<int> fldOrganId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblShomareSelect>("spr_tblShomareSelect", fieldNameParameter, valueParameter, idParameter, fldOrganIdParameter, hParameter);
        }
    
        public virtual int spr_tblShomareUpdate(Nullable<int> fldId, Nullable<int> fldRadifId, string fldShomare, Nullable<byte> fldTedadTabaghat, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIp, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldRadifIdParameter = fldRadifId.HasValue ?
                new ObjectParameter("fldRadifId", fldRadifId) :
                new ObjectParameter("fldRadifId", typeof(int));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldTedadTabaghatParameter = fldTedadTabaghat.HasValue ?
                new ObjectParameter("fldTedadTabaghat", fldTedadTabaghat) :
                new ObjectParameter("fldTedadTabaghat", typeof(byte));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIpParameter = fldIp != null ?
                new ObjectParameter("fldIp", fldIp) :
                new ObjectParameter("fldIp", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblShomareUpdate", fldIdParameter, fldRadifIdParameter, fldShomareParameter, fldTedadTabaghatParameter, fldOrganIdParameter, fldUserIdParameter, fldIpParameter, fldDescParameter);
        }
    
        public virtual int spr_tblGhabreAmanatDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGhabreAmanatDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblGhabreAmanatInsert(Nullable<int> fldShomareId, Nullable<int> fldEmployeeId, Nullable<int> fldOrganId, Nullable<int> fldTarikhRezerv, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldShomareIdParameter = fldShomareId.HasValue ?
                new ObjectParameter("fldShomareId", fldShomareId) :
                new ObjectParameter("fldShomareId", typeof(int));
    
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldTarikhRezervParameter = fldTarikhRezerv.HasValue ?
                new ObjectParameter("fldTarikhRezerv", fldTarikhRezerv) :
                new ObjectParameter("fldTarikhRezerv", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGhabreAmanatInsert", fldShomareIdParameter, fldEmployeeIdParameter, fldOrganIdParameter, fldTarikhRezervParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblGhabreAmanatSelect> spr_tblGhabreAmanatSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblGhabreAmanatSelect>("spr_tblGhabreAmanatSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblGhabreAmanatUpdate(Nullable<int> fldId, Nullable<int> fldShomareId, Nullable<int> fldEmployeeId, Nullable<int> fldOrganId, Nullable<int> fldTarikhRezerv, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldShomareIdParameter = fldShomareId.HasValue ?
                new ObjectParameter("fldShomareId", fldShomareId) :
                new ObjectParameter("fldShomareId", typeof(int));
    
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldTarikhRezervParameter = fldTarikhRezerv.HasValue ?
                new ObjectParameter("fldTarikhRezerv", fldTarikhRezerv) :
                new ObjectParameter("fldTarikhRezerv", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblGhabreAmanatUpdate", fldIdParameter, fldShomareIdParameter, fldEmployeeIdParameter, fldOrganIdParameter, fldTarikhRezervParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblMotevaffaDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMotevaffaDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblMotevaffaInsert(Nullable<int> fldShomareId, Nullable<int> fldEmployeeId, Nullable<int> fldCauseOfDeathId, Nullable<int> fldTarikhFot, Nullable<int> fldTarikhDafn, Nullable<int> fldMahalFotId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldShomareIdParameter = fldShomareId.HasValue ?
                new ObjectParameter("fldShomareId", fldShomareId) :
                new ObjectParameter("fldShomareId", typeof(int));
    
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldCauseOfDeathIdParameter = fldCauseOfDeathId.HasValue ?
                new ObjectParameter("fldCauseOfDeathId", fldCauseOfDeathId) :
                new ObjectParameter("fldCauseOfDeathId", typeof(int));
    
            var fldTarikhFotParameter = fldTarikhFot.HasValue ?
                new ObjectParameter("fldTarikhFot", fldTarikhFot) :
                new ObjectParameter("fldTarikhFot", typeof(int));
    
            var fldTarikhDafnParameter = fldTarikhDafn.HasValue ?
                new ObjectParameter("fldTarikhDafn", fldTarikhDafn) :
                new ObjectParameter("fldTarikhDafn", typeof(int));
    
            var fldMahalFotIdParameter = fldMahalFotId.HasValue ?
                new ObjectParameter("fldMahalFotId", fldMahalFotId) :
                new ObjectParameter("fldMahalFotId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMotevaffaInsert", fldShomareIdParameter, fldEmployeeIdParameter, fldCauseOfDeathIdParameter, fldTarikhFotParameter, fldTarikhDafnParameter, fldMahalFotIdParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblMotevaffaSelect> spr_tblMotevaffaSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblMotevaffaSelect>("spr_tblMotevaffaSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblMotevaffaUpdate(Nullable<int> fldId, Nullable<int> fldCauseOfDeathId, Nullable<int> fldGhabreAmanatId, Nullable<int> fldTarikhFot, Nullable<int> fldTarikhDafn, Nullable<int> fldMahalFotId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldCauseOfDeathIdParameter = fldCauseOfDeathId.HasValue ?
                new ObjectParameter("fldCauseOfDeathId", fldCauseOfDeathId) :
                new ObjectParameter("fldCauseOfDeathId", typeof(int));
    
            var fldGhabreAmanatIdParameter = fldGhabreAmanatId.HasValue ?
                new ObjectParameter("fldGhabreAmanatId", fldGhabreAmanatId) :
                new ObjectParameter("fldGhabreAmanatId", typeof(int));
    
            var fldTarikhFotParameter = fldTarikhFot.HasValue ?
                new ObjectParameter("fldTarikhFot", fldTarikhFot) :
                new ObjectParameter("fldTarikhFot", typeof(int));
    
            var fldTarikhDafnParameter = fldTarikhDafn.HasValue ?
                new ObjectParameter("fldTarikhDafn", fldTarikhDafn) :
                new ObjectParameter("fldTarikhDafn", typeof(int));
    
            var fldMahalFotIdParameter = fldMahalFotId.HasValue ?
                new ObjectParameter("fldMahalFotId", fldMahalFotId) :
                new ObjectParameter("fldMahalFotId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMotevaffaUpdate", fldIdParameter, fldCauseOfDeathIdParameter, fldGhabreAmanatIdParameter, fldTarikhFotParameter, fldTarikhDafnParameter, fldMahalFotIdParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblMahalFotDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMahalFotDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblMahalFotInsert(string fldNameMahal, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldNameMahalParameter = fldNameMahal != null ?
                new ObjectParameter("fldNameMahal", fldNameMahal) :
                new ObjectParameter("fldNameMahal", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMahalFotInsert", fldNameMahalParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblMahalFotSelect> spr_tblMahalFotSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblMahalFotSelect>("spr_tblMahalFotSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblMahalFotUpdate(Nullable<int> fldId, string fldNameMahal, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldNameMahalParameter = fldNameMahal != null ?
                new ObjectParameter("fldNameMahal", fldNameMahal) :
                new ObjectParameter("fldNameMahal", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMahalFotUpdate", fldIdParameter, fldNameMahalParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_selectTabaghe> spr_selectTabaghe(Nullable<int> shomareId, Nullable<int> id)
        {
            var shomareIdParameter = shomareId.HasValue ?
                new ObjectParameter("shomareId", shomareId) :
                new ObjectParameter("shomareId", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_selectTabaghe>("spr_selectTabaghe", shomareIdParameter, idParameter);
        }
    
        public virtual int spr_InsertEmployee(ObjectParameter fldEmployeeId, string fldCodeMeli, string fldCodeMoshakhase, string fldName, string fldFamily, string fldSh_Sh, string fldFatherName, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldCodeMeliParameter = fldCodeMeli != null ?
                new ObjectParameter("fldCodeMeli", fldCodeMeli) :
                new ObjectParameter("fldCodeMeli", typeof(string));
    
            var fldCodeMoshakhaseParameter = fldCodeMoshakhase != null ?
                new ObjectParameter("fldCodeMoshakhase", fldCodeMoshakhase) :
                new ObjectParameter("fldCodeMoshakhase", typeof(string));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldFamilyParameter = fldFamily != null ?
                new ObjectParameter("fldFamily", fldFamily) :
                new ObjectParameter("fldFamily", typeof(string));
    
            var fldSh_ShParameter = fldSh_Sh != null ?
                new ObjectParameter("fldSh_Sh", fldSh_Sh) :
                new ObjectParameter("fldSh_Sh", typeof(string));
    
            var fldFatherNameParameter = fldFatherName != null ?
                new ObjectParameter("fldFatherName", fldFatherName) :
                new ObjectParameter("fldFatherName", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_InsertEmployee", fldEmployeeId, fldCodeMeliParameter, fldCodeMoshakhaseParameter, fldNameParameter, fldFamilyParameter, fldSh_ShParameter, fldFatherNameParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_UpdateGheteKhali(Nullable<int> fldVadiSalamId, Nullable<int> fldGheteId, string fldNameGhete, Nullable<int> fldOrganid, Nullable<int> fldUserId, string fldIP, string fldDesc, Nullable<int> fldRadif, Nullable<int> fldShomare, string fldTabaghe)
        {
            var fldVadiSalamIdParameter = fldVadiSalamId.HasValue ?
                new ObjectParameter("fldVadiSalamId", fldVadiSalamId) :
                new ObjectParameter("fldVadiSalamId", typeof(int));
    
            var fldGheteIdParameter = fldGheteId.HasValue ?
                new ObjectParameter("fldGheteId", fldGheteId) :
                new ObjectParameter("fldGheteId", typeof(int));
    
            var fldNameGheteParameter = fldNameGhete != null ?
                new ObjectParameter("fldNameGhete", fldNameGhete) :
                new ObjectParameter("fldNameGhete", typeof(string));
    
            var fldOrganidParameter = fldOrganid.HasValue ?
                new ObjectParameter("fldOrganid", fldOrganid) :
                new ObjectParameter("fldOrganid", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldRadifParameter = fldRadif.HasValue ?
                new ObjectParameter("fldRadif", fldRadif) :
                new ObjectParameter("fldRadif", typeof(int));
    
            var fldShomareParameter = fldShomare.HasValue ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(int));
    
            var fldTabagheParameter = fldTabaghe != null ?
                new ObjectParameter("fldTabaghe", fldTabaghe) :
                new ObjectParameter("fldTabaghe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateGheteKhali", fldVadiSalamIdParameter, fldGheteIdParameter, fldNameGheteParameter, fldOrganidParameter, fldUserIdParameter, fldIPParameter, fldDescParameter, fldRadifParameter, fldShomareParameter, fldTabagheParameter);
        }
    
        public virtual ObjectResult<spr_SelectGheteDetail> spr_SelectGheteDetail(Nullable<int> gheteId)
        {
            var gheteIdParameter = gheteId.HasValue ?
                new ObjectParameter("GheteId", gheteId) :
                new ObjectParameter("GheteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectGheteDetail>("spr_SelectGheteDetail", gheteIdParameter);
        }
    
        public virtual int spr_DeleteAllTablesOnGhete(Nullable<int> fldGheteId, Nullable<int> fldUserId, string fldIP)
        {
            var fldGheteIdParameter = fldGheteId.HasValue ?
                new ObjectParameter("fldGheteId", fldGheteId) :
                new ObjectParameter("fldGheteId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_DeleteAllTablesOnGhete", fldGheteIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_RptGhabrPor_Khali> spr_RptGhabrPor_Khali(string fieldname, Nullable<int> vadiid, Nullable<int> gheteid, Nullable<int> radifid, Nullable<int> shomareid, Nullable<int> organid)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var vadiidParameter = vadiid.HasValue ?
                new ObjectParameter("Vadiid", vadiid) :
                new ObjectParameter("Vadiid", typeof(int));
    
            var gheteidParameter = gheteid.HasValue ?
                new ObjectParameter("Gheteid", gheteid) :
                new ObjectParameter("Gheteid", typeof(int));
    
            var radifidParameter = radifid.HasValue ?
                new ObjectParameter("radifid", radifid) :
                new ObjectParameter("radifid", typeof(int));
    
            var shomareidParameter = shomareid.HasValue ?
                new ObjectParameter("shomareid", shomareid) :
                new ObjectParameter("shomareid", typeof(int));
    
            var organidParameter = organid.HasValue ?
                new ObjectParameter("organid", organid) :
                new ObjectParameter("organid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_RptGhabrPor_Khali>("spr_RptGhabrPor_Khali", fieldnameParameter, vadiidParameter, gheteidParameter, radifidParameter, shomareidParameter, organidParameter);
        }
    
        public virtual ObjectResult<spr_SelectInfoEmployeeInGhabrAmanat> spr_SelectInfoEmployeeInGhabrAmanat(Nullable<int> shomareId, Nullable<byte> shomareTabaghe)
        {
            var shomareIdParameter = shomareId.HasValue ?
                new ObjectParameter("shomareId", shomareId) :
                new ObjectParameter("shomareId", typeof(int));
    
            var shomareTabagheParameter = shomareTabaghe.HasValue ?
                new ObjectParameter("ShomareTabaghe", shomareTabaghe) :
                new ObjectParameter("ShomareTabaghe", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectInfoEmployeeInGhabrAmanat>("spr_SelectInfoEmployeeInGhabrAmanat", shomareIdParameter, shomareTabagheParameter);
        }
    
        public virtual int spr_UpdateTedadTabaghat(string fldShomare, Nullable<int> fldIdGhete, string nameGhate, string desc, Nullable<int> userId, Nullable<int> organid)
        {
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldIdGheteParameter = fldIdGhete.HasValue ?
                new ObjectParameter("fldIdGhete", fldIdGhete) :
                new ObjectParameter("fldIdGhete", typeof(int));
    
            var nameGhateParameter = nameGhate != null ?
                new ObjectParameter("NameGhate", nameGhate) :
                new ObjectParameter("NameGhate", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var organidParameter = organid.HasValue ?
                new ObjectParameter("organid", organid) :
                new ObjectParameter("organid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateTedadTabaghat", fldShomareParameter, fldIdGheteParameter, nameGhateParameter, descParameter, userIdParameter, organidParameter);
        }
    
        public virtual int spr_tblCodeDaramadAramestanDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCodeDaramadAramestanDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblCodeDaramadAramestanInsert(Nullable<int> fldCodeDaramadId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldCodeDaramadIdParameter = fldCodeDaramadId.HasValue ?
                new ObjectParameter("fldCodeDaramadId", fldCodeDaramadId) :
                new ObjectParameter("fldCodeDaramadId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCodeDaramadAramestanInsert", fldCodeDaramadIdParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblCodeDaramadAramestanSelect> spr_tblCodeDaramadAramestanSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblCodeDaramadAramestanSelect>("spr_tblCodeDaramadAramestanSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblCodeDaramadAramestanUpdate(Nullable<int> fldId, Nullable<int> fldCodeDaramadId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldCodeDaramadIdParameter = fldCodeDaramadId.HasValue ?
                new ObjectParameter("fldCodeDaramadId", fldCodeDaramadId) :
                new ObjectParameter("fldCodeDaramadId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCodeDaramadAramestanUpdate", fldIdParameter, fldCodeDaramadIdParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblActionsDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblActionsDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblActionsInsert(string fldTitleAction, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldTitleActionParameter = fldTitleAction != null ?
                new ObjectParameter("fldTitleAction", fldTitleAction) :
                new ObjectParameter("fldTitleAction", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblActionsInsert", fldTitleActionParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblActionsSelect> spr_tblActionsSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblActionsSelect>("spr_tblActionsSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblActionsUpdate(Nullable<int> fldId, string fldTitleAction, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTitleActionParameter = fldTitleAction != null ?
                new ObjectParameter("fldTitleAction", fldTitleAction) :
                new ObjectParameter("fldTitleAction", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblActionsUpdate", fldIdParameter, fldTitleActionParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblKartablDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartablDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblKartablInsert(string fldTitleKartabl, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc, Nullable<bool> fldHaveEtmam, Nullable<bool> fldHaveEbtal)
        {
            var fldTitleKartablParameter = fldTitleKartabl != null ?
                new ObjectParameter("fldTitleKartabl", fldTitleKartabl) :
                new ObjectParameter("fldTitleKartabl", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldHaveEtmamParameter = fldHaveEtmam.HasValue ?
                new ObjectParameter("fldHaveEtmam", fldHaveEtmam) :
                new ObjectParameter("fldHaveEtmam", typeof(bool));
    
            var fldHaveEbtalParameter = fldHaveEbtal.HasValue ?
                new ObjectParameter("fldHaveEbtal", fldHaveEbtal) :
                new ObjectParameter("fldHaveEbtal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartablInsert", fldTitleKartablParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter, fldHaveEtmamParameter, fldHaveEbtalParameter);
        }
    
        public virtual ObjectResult<spr_tblKartablSelect> spr_tblKartablSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblKartablSelect>("spr_tblKartablSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblKartablUpdate(Nullable<int> fldId, string fldTitleKartabl, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc, Nullable<bool> fldHaveEtmam, Nullable<bool> fldHaveEbtal)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTitleKartablParameter = fldTitleKartabl != null ?
                new ObjectParameter("fldTitleKartabl", fldTitleKartabl) :
                new ObjectParameter("fldTitleKartabl", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldHaveEtmamParameter = fldHaveEtmam.HasValue ?
                new ObjectParameter("fldHaveEtmam", fldHaveEtmam) :
                new ObjectParameter("fldHaveEtmam", typeof(bool));
    
            var fldHaveEbtalParameter = fldHaveEbtal.HasValue ?
                new ObjectParameter("fldHaveEbtal", fldHaveEbtal) :
                new ObjectParameter("fldHaveEbtal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartablUpdate", fldIdParameter, fldTitleKartablParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter, fldHaveEtmamParameter, fldHaveEbtalParameter);
        }
    
        public virtual int spr_tblAction_KartablDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAction_KartablDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblAction_KartablInsert(Nullable<int> fldActionId, Nullable<int> fldKartablId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldKartablIdParameter = fldKartablId.HasValue ?
                new ObjectParameter("fldKartablId", fldKartablId) :
                new ObjectParameter("fldKartablId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAction_KartablInsert", fldActionIdParameter, fldKartablIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblAction_KartablSelect> spr_tblAction_KartablSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblAction_KartablSelect>("spr_tblAction_KartablSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblAction_KartablUpdate(Nullable<int> fldId, Nullable<int> fldActionId, Nullable<int> fldKartablId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldKartablIdParameter = fldKartablId.HasValue ?
                new ObjectParameter("fldKartablId", fldKartablId) :
                new ObjectParameter("fldKartablId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAction_KartablUpdate", fldIdParameter, fldActionIdParameter, fldKartablIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_UpdateOrderKartabl(Nullable<int> kartablid, Nullable<int> orderid, Nullable<int> userId)
        {
            var kartablidParameter = kartablid.HasValue ?
                new ObjectParameter("kartablid", kartablid) :
                new ObjectParameter("kartablid", typeof(int));
    
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateOrderKartabl", kartablidParameter, orderidParameter, userIdParameter);
        }
    
        public virtual int spr_tblRequestAmanatDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRequestAmanatDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblRequestAmanatInsert(Nullable<int> fldEmployeeId, Nullable<int> fldShomareId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldShomareIdParameter = fldShomareId.HasValue ?
                new ObjectParameter("fldShomareId", fldShomareId) :
                new ObjectParameter("fldShomareId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRequestAmanatInsert", fldEmployeeIdParameter, fldShomareIdParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblRequestAmanatSelect> spr_tblRequestAmanatSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblRequestAmanatSelect>("spr_tblRequestAmanatSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblRequestAmanatUpdate(Nullable<int> fldId, Nullable<int> fldEmployeeId, Nullable<int> fldShomareId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldShomareIdParameter = fldShomareId.HasValue ?
                new ObjectParameter("fldShomareId", fldShomareId) :
                new ObjectParameter("fldShomareId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRequestAmanatUpdate", fldIdParameter, fldEmployeeIdParameter, fldShomareIdParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblKartabl_RequestDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartabl_RequestDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblKartabl_RequestInsert(Nullable<int> fldKartablId, Nullable<int> fldActionId, Nullable<int> fldRequestId, Nullable<int> fldKartablNextId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldKartablIdParameter = fldKartablId.HasValue ?
                new ObjectParameter("fldKartablId", fldKartablId) :
                new ObjectParameter("fldKartablId", typeof(int));
    
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldRequestIdParameter = fldRequestId.HasValue ?
                new ObjectParameter("fldRequestId", fldRequestId) :
                new ObjectParameter("fldRequestId", typeof(int));
    
            var fldKartablNextIdParameter = fldKartablNextId.HasValue ?
                new ObjectParameter("fldKartablNextId", fldKartablNextId) :
                new ObjectParameter("fldKartablNextId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartabl_RequestInsert", fldKartablIdParameter, fldActionIdParameter, fldRequestIdParameter, fldKartablNextIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblKartabl_RequestSelect> spr_tblKartabl_RequestSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblKartabl_RequestSelect>("spr_tblKartabl_RequestSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblKartabl_RequestUpdate(Nullable<int> fldId, Nullable<int> fldKartablId, Nullable<int> fldActionId, Nullable<int> fldRequestId, Nullable<int> fldKartablNextId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldKartablIdParameter = fldKartablId.HasValue ?
                new ObjectParameter("fldKartablId", fldKartablId) :
                new ObjectParameter("fldKartablId", typeof(int));
    
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldRequestIdParameter = fldRequestId.HasValue ?
                new ObjectParameter("fldRequestId", fldRequestId) :
                new ObjectParameter("fldRequestId", typeof(int));
    
            var fldKartablNextIdParameter = fldKartablNextId.HasValue ?
                new ObjectParameter("fldKartablNextId", fldKartablNextId) :
                new ObjectParameter("fldKartablNextId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblKartabl_RequestUpdate", fldIdParameter, fldKartablIdParameter, fldActionIdParameter, fldRequestIdParameter, fldKartablNextIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_SelectTimeLine> spr_SelectTimeLine(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("requestId", requestId) :
                new ObjectParameter("requestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectTimeLine>("spr_SelectTimeLine", requestIdParameter);
        }
    
        public virtual int spr_tblNextKartablDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblNextKartablDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblNextKartablInsert(Nullable<int> fldKartablNextId, Nullable<int> fldActionId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldKartablNextIdParameter = fldKartablNextId.HasValue ?
                new ObjectParameter("fldKartablNextId", fldKartablNextId) :
                new ObjectParameter("fldKartablNextId", typeof(int));
    
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblNextKartablInsert", fldKartablNextIdParameter, fldActionIdParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblNextKartablSelect> spr_tblNextKartablSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblNextKartablSelect>("spr_tblNextKartablSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblNextKartablUpdate(Nullable<int> fldId, Nullable<int> fldKartablNextId, Nullable<int> fldActionId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldKartablNextIdParameter = fldKartablNextId.HasValue ?
                new ObjectParameter("fldKartablNextId", fldKartablNextId) :
                new ObjectParameter("fldKartablNextId", typeof(int));
    
            var fldActionIdParameter = fldActionId.HasValue ?
                new ObjectParameter("fldActionId", fldActionId) :
                new ObjectParameter("fldActionId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblNextKartablUpdate", fldIdParameter, fldKartablNextIdParameter, fldActionIdParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_UpdateEtmamCharkhe(Nullable<int> fldId, Nullable<int> userId, string iP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateEtmamCharkhe", fldIdParameter, userIdParameter, iPParameter);
        }
    
        public virtual int spr_UpdateRequestForEbtal(Nullable<int> fldId, Nullable<int> fldUserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateRequestForEbtal", fldIdParameter, fldUserIdParameter, fldIPParameter);
        }
    }
}
