//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class prs_tblCalcHeaderSelect
    {
        public int fldId { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public int fldNobatPardakhtId { get; set; }
        public int fldOrganId { get; set; }
        public byte fldStatus { get; set; }
        public string fldIp { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldStatusName { get; set; }
        public Nullable<int> fldQueue { get; set; }
        public string fldNameOrgan { get; set; }
        public string fldName { get; set; }
        public string fldMonthName { get; set; }
        public string fldTarikh { get; set; }
        public Nullable<byte> fldCalcType { get; set; }
        public string fldCalcTypeName { get; set; }
        public Nullable<int> fldQueueTime { get; set; }
    }
}
