//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class SelectPishbiniBudje_SalGhabl
    {
        public string fldCode { get; set; }
        public string fldTitle { get; set; }
        public Nullable<long> Col1 { get; set; }
        public Nullable<long> Col10 { get; set; }
        public Nullable<long> Col2 { get; set; }
        public Nullable<long> Col3 { get; set; }
        public Nullable<long> Col4 { get; set; }
        public Nullable<long> Col5 { get; set; }
        public Nullable<long> Col6 { get; set; }
        public Nullable<long> Col7 { get; set; }
        public Nullable<long> Col8 { get; set; }
        public Nullable<long> Col9 { get; set; }
        public int last { get; set; }
        public int fldCodingId { get; set; }
        public string fldNameDarasad { get; set; }
        public int fldflagSanad { get; set; }
    }
}
