//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDasteCheckSelect
    {
        public int fldId { get; set; }
        public int fldIdOlgoCheck { get; set; }
        public string fldMoshakhaseDasteCheck { get; set; }
        public byte fldTedadBarg { get; set; }
        public string fldShoroeSeriyal { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldOlgu { get; set; }
        public int fldIdShomareHesab { get; set; }
        public string fldShomareHesab { get; set; }
        public string fldShobeName { get; set; }
        public string fldBankName { get; set; }
        public int fldOrganId { get; set; }
    }
}
