//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_ListCodeDaramad_ShomareHesabWithOrganId
    {
        public int fldId { get; set; }
        public string fldDaramadCode { get; set; }
        public string fldDaramadTitle { get; set; }
        public string fldNameVahed { get; set; }
        public string fldShomareHesab { get; set; }
        public bool fldMashmooleArzesheAfzoode { get; set; }
        public bool fldMashmooleKarmozd { get; set; }
        public string fldDesc { get; set; }
        public int fldShomareHsabCodeDaramadId { get; set; }
        public byte fldShorooshenaseGhabz { get; set; }
        public int fldShomareHesabId { get; set; }
        public bool fldStatus { get; set; }
    }
}
