//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectRannadeInPlaque
    {
        public int fldRananadeId { get; set; }
        public string fldNameRanande { get; set; }
        public Nullable<bool> IsKhali { get; set; }
        public string fldNameKhodro { get; set; }
        public int fldTypeKhodro { get; set; }
    }
}
