//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCommisionSelect_Post
    {
        public int fldid { get; set; }
        public string fldName { get; set; }
        public string fldFatherName { get; set; }
        public string fldO_postEjraee_title { get; set; }
    }
}
