//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblAshkhaseHoghoghiSelect
    {
        public int fldId { get; set; }
        public string fldShenaseMelli { get; set; }
        public string fldName { get; set; }
        public string fldShomareSabt { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public byte fldTypeShakhs { get; set; }
        public string fldTypeShakhsName { get; set; }
        public byte fldSayer { get; set; }
        public string fldSayerName { get; set; }
    }
}
