//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDocumentRecorde_File_BookMarkSelect
    {
        public int fldId { get; set; }
        public byte[] fldImage { get; set; }
        public string fldPasvand { get; set; }
        public Nullable<int> fldArchiveTreeId { get; set; }
        public Nullable<bool> fldIsBookMark { get; set; }
        public string fldTitle { get; set; }
    }
}
