//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBazneshastegi
    {
        public string fldSh_Personali { get; set; }
        public string fldCodemeli { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldTarikhTavalod { get; set; }
        public Nullable<int> fldMahalTavalodId { get; set; }
        public string fldJensiyat { get; set; }
        public byte fldKarkard { get; set; }
        public int fldExExpert { get; set; }
        public string fldTarikhMazad30Sal { get; set; }
        public Nullable<int> fldStatusTaaholId { get; set; }
        public string fldNesbatBaz { get; set; }
        public string fldEsarBazneshastegi { get; set; }
        public string s_gheyrerasmi { get; set; }
        public string s_rasmi { get; set; }
        public string fldTaaholBazneshastegi { get; set; }
        public Nullable<byte> fldTedadFarzand { get; set; }
        public Nullable<int> fldMadrakId { get; set; }
        public string fldMadrakTahsili { get; set; }
        public string TitleReshte { get; set; }
        public byte fldNezamVazifeId { get; set; }
        public string fldNezamVazifeTitle { get; set; }
        public string fldRasteShoghli { get; set; }
        public string fldReshteShoghli { get; set; }
        public string OrganPost { get; set; }
        public Nullable<byte> fldGroup { get; set; }
        public byte fldMoreGroup { get; set; }
        public int fldEsargariId { get; set; }
        public string fldTabaghe { get; set; }
        public string fldTarikhEstekhdam { get; set; }
        public string fldTypeEstekhdamBaz { get; set; }
        public string fldMobile { get; set; }
        public int fldMazad30Sal { get; set; }
        public string fldTarikhEjra { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public int fldMashmolBime { get; set; }
        public int fldBimePersonal { get; set; }
        public int fldBimeKarFarma { get; set; }
        public int fldMashmolBimeMoavaghe { get; set; }
        public int fldBimePersonalMoavaghe { get; set; }
        public int fldBimeKarfarmaMoavaghe { get; set; }
        public int fldMogharari { get; set; }
        public string fldTypeHokm { get; set; }
        public int fldPersonalId { get; set; }
        public string CityName { get; set; }
        public string CityNameSodoor { get; set; }
        public string StateNameSodoor { get; set; }
        public string fldJobDesc { get; set; }
        public int h_paye { get; set; }
        public int sanavat { get; set; }
        public int paye { get; set; }
        public int sanavat_basiji { get; set; }
        public int sanavat_isar { get; set; }
        public int foghshoghl { get; set; }
        public int takhasosi { get; set; }
        public int made26 { get; set; }
        public int modiryati { get; set; }
        public int barjastegi { get; set; }
        public int tatbigh { get; set; }
        public int fogh_isar { get; set; }
        public int abohava { get; set; }
        public int tashilat { get; set; }
        public int sakhtikar { get; set; }
        public int tadil { get; set; }
        public Nullable<int> band_y { get; set; }
        public int riali { get; set; }
        public int jazb9 { get; set; }
        public Nullable<int> jazb { get; set; }
        public Nullable<int> makhsos { get; set; }
        public Nullable<int> vije { get; set; }
        public int olad { get; set; }
        public int ayelemandi { get; set; }
        public int kharobar { get; set; }
        public int maskan { get; set; }
        public int nobatkari { get; set; }
        public int bon { get; set; }
        public int jazb_tabsare { get; set; }
        public int talash { get; set; }
        public int jebhe { get; set; }
        public int janbazi { get; set; }
        public int sayer { get; set; }
        public int ezafekar { get; set; }
        public int mamoriat { get; set; }
        public int tatilkari { get; set; }
        public int s_payankhedmat { get; set; }
        public int ghazai { get; set; }
        public int ashoora { get; set; }
        public int zaribtadil { get; set; }
        public int jazbTakhasosi { get; set; }
        public int jazbtadil { get; set; }
        public int hadaghaltadil { get; set; }
        public int tatbigh1 { get; set; }
        public int tarmim { get; set; }
        public string fldHalateEstekhdam { get; set; }
        public Nullable<int> jame { get; set; }
    }
}
