//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblSpecialPermissionSelect
    {
        public int fldId { get; set; }
        public int fldUserSelectId { get; set; }
        public int fldChartOrganId { get; set; }
        public int fldOpertionId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameEmloyee { get; set; }
        public string fldTitleChart { get; set; }
        public string fldTitleOpr { get; set; }
    }
}
