//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblInternalAssignmentReceiverSelect
    {
        public int fldID { get; set; }
        public int fldAssignmentID { get; set; }
        public int fldReceiverComisionID { get; set; }
        public int fldAssignmentStatusID { get; set; }
        public int fldAssignmentTypeID { get; set; }
        public int fldBoxID { get; set; }
        public string fldLetterReadDate { get; set; }
        public bool fldShowTypeT_F { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public int fldOrganId { get; set; }
        public string fldIP { get; set; }
        public string fldBoxName { get; set; }
        public string fldStatusName { get; set; }
        public string fldTypeAssignment { get; set; }
        public string fldName_Family { get; set; }
    }
}
