//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblRegistrationContractSelect
    {
        public int fldId { get; set; }
        public int fldWarrantyId { get; set; }
        public byte fldRoleOrgan { get; set; }
        public string fldRoleOrgan_Name { get; set; }
        public string fldTitleContract { get; set; }
        public int fldAshkhasId { get; set; }
        public byte fldSuplyMaterialsType { get; set; }
        public string fldSuplyMaterialsType_Name { get; set; }
        public long fldAmountContract { get; set; }
        public string fldNumber { get; set; }
        public string fldTarikh { get; set; }
        public Nullable<int> fldShobeId { get; set; }
        public string fldSepamNum { get; set; }
        public string fldTarikhEtmam { get; set; }
        public string fldStartContract { get; set; }
        public string fldEndContract { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIp { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldWarentytype_Name { get; set; }
        public string fldCodeMelli { get; set; }
        public string fldName_Shakhs { get; set; }
        public string fldName_Shobe { get; set; }
        public int fldCodeSHobe { get; set; }
        public Nullable<int> fldBankId { get; set; }
        public string fldBankName { get; set; }
    }
}
