//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectSavedMessage
    {
        public string fldTitleMessge { get; set; }
        public string fldMatn { get; set; }
        public string fldtarikh { get; set; }
        public int fldMessageId { get; set; }
        public Nullable<int> fldLetterId { get; set; }
        public int HaveAttach { get; set; }
        public string fldCommision { get; set; }
        public string LetterRecievers { get; set; }
        public string fldDesc { get; set; }
    }
}
