//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKosuratParametriGroupSelect
    {
        public int fldPersonalInfoId { get; set; }
        public string fldName { get; set; }
        public string fldName_Father { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public string fldTitle { get; set; }
        public int fldId { get; set; }
        public int fldNoeEstekhdamId { get; set; }
        public Nullable<bool> fldChecked { get; set; }
    }
}
