//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCheck_FactorSelect
    {
        public int fldId { get; set; }
        public int fldCheckSadereId { get; set; }
        public Nullable<int> fldFactorId { get; set; }
        public Nullable<int> fldContractId { get; set; }
        public Nullable<int> fldTankhahGroupId { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserId { get; set; }
    }
}
