//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblTarh_KhedmatSelect
    {
        public int fldId { get; set; }
        public int fldProgramId { get; set; }
        public string fldCod { get; set; }
        public string fldTitle { get; set; }
        public byte fldType { get; set; }
        public string fldTarh_KhedmatType { get; set; }
        public int fldOrganId { get; set; }
        public System.DateTime flddate { get; set; }
        public string fldDesc { get; set; }
        public int fldUserId { get; set; }
        public string fldTitle_Program { get; set; }
        public string fldTitle_Mamoriyat { get; set; }
        public string fldCod_Mamoriyat { get; set; }
        public string fldCod_Program { get; set; }
        public short fldYear { get; set; }
    }
}
