//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblOnAccountSelect
    {
        public int fldId { get; set; }
        public string fldCodeMeli { get; set; }
        public int fldPersonalId { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public string fldTitle { get; set; }
        public byte fldNobatePardakt { get; set; }
        public int fldKhalesPardakhti { get; set; }
        public int fldUserId { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public bool fldFlag { get; set; }
        public string fldName { get; set; }
        public int fldOrganId { get; set; }
        public bool fldGhatei { get; set; }
        public string fldShomareHesab { get; set; }
        public string fldGhateiName { get; set; }
    }
}
