//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblOrganizationSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public Nullable<int> fldPId { get; set; }
        public int fldFileId { get; set; }
        public int fldCityId { get; set; }
        public string fldCodePosti { get; set; }
        public string fldTelphon { get; set; }
        public string fldAddress { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldCityName { get; set; }
        public string fldCodAnformatic { get; set; }
        public byte fldCodKhedmat { get; set; }
        public string fldShenaseMelli { get; set; }
        public string fldCodEghtesadi { get; set; }
        public string fldShomareSabt { get; set; }
        public int fldAshkhaseHoghoghiId { get; set; }
        public string FldNameAshkhaseHoghoghi { get; set; }
        public int fldStateId { get; set; }
    }
}
