//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBime_Header_DBF
    {
        public string fldEmployerName { get; set; }
        public string fldAddress { get; set; }
        public int DSK_KIND { get; set; }
        public int DSK_Disc { get; set; }
        public int DSK_NUM { get; set; }
        public int fldKarkard { get; set; }
        public long fldRozane { get; set; }
        public int fldPayeSanavati { get; set; }
        public long fldMazayaMahiyane { get; set; }
        public long fldMashmolBime { get; set; }
        public long fldItem { get; set; }
        public long fldBimePersonal { get; set; }
        public long fldTaahol { get; set; }
        public long fldMahane { get; set; }
        public int DSK_Rate { get; set; }
        public int DSK_PRate { get; set; }
        public int DSK_Bimh { get; set; }
        public string Mon_Pay { get; set; }
        public string DSK_ID { get; set; }
        public string fldWorkShopName { get; set; }
        public long fldBimeKarFarma { get; set; }
        public long fldBimeBikari { get; set; }
    }
}
