//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblVaziyatEsargariSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public bool fldMoafAsBime { get; set; }
        public bool fldMoafAsMaliyat { get; set; }
        public bool fldMoafAsBimeOmr { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldMoafAsBimeName { get; set; }
        public string fldMoafAsMaliyatName { get; set; }
        public string fldMoafAsBimeOmrName { get; set; }
        public bool fldMoafAsBimeTakmili { get; set; }
        public string fldMoafAsBimeTakmiliName { get; set; }
    }
}
