//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectDetailSodoorFish
    {
        public string fldSharheCodeDaramad { get; set; }
        public long fldAsliValue { get; set; }
        public long fldAvarezValue { get; set; }
        public long fldMaliyatValue { get; set; }
        public int fldCodeDaramadId { get; set; }
        public int fldShomareHesabId { get; set; }
        public string fldShomareHesab { get; set; }
        public byte fldShorooshenaseGhabz { get; set; }
        public Nullable<long> fldAmuzeshParvareshValue { get; set; }
    }
}
