//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDaramadGroup_ParametrValuesSelect
    {
        public int fldId { get; set; }
        public int fldElamAvarezId { get; set; }
        public int fldParametrGroupDaramadId { get; set; }
        public string fldValue { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldFnName { get; set; }
    }
}
