//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKarKardHokmSelect
    {
        public int fldId { get; set; }
        public int fldKarkardId { get; set; }
        public int fldHokmId { get; set; }
        public decimal fldRoze { get; set; }
        public decimal fldGheybat { get; set; }
    }
}
