//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectInfoEmployeeInGhabrAmanat
    {
        public int fldid { get; set; }
        public string fldShomareTabaghe { get; set; }
        public string fldName_Family { get; set; }
        public string fldFatherName { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldMeli_Moshakhase { get; set; }
        public string fldTarikhRezerv { get; set; }
        public string fldTarikhFot { get; set; }
        public string fldNameMahal { get; set; }
        public string fldReason { get; set; }
        public string fldTarikhDafn { get; set; }
    }
}
