//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblRemittance_DetailsSelect
    {
        public int fldId { get; set; }
        public int fldRemittanceId { get; set; }
        public int fldKalaId { get; set; }
        public string fldMaxTon { get; set; }
        public bool fldControlLimit { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldKalaName { get; set; }
        public string fldTitleHeader { get; set; }
        public int fldExistsVazn { get; set; }
    }
}
