//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblBudgetPayHeaderSelect
    {
        public int fldId { get; set; }
        public int fldFiscalYearId { get; set; }
        public Nullable<int> fldItemsHoghughiId { get; set; }
        public Nullable<int> fldParametrId { get; set; }
        public int fldBudgetCode { get; set; }
        public int fldUserId { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldTitle { get; set; }
        public string fldTitleBudget { get; set; }
        public short fldYear { get; set; }
        public string fldTitleEstkhdam { get; set; }
        public string fldTypeEstekhdamId { get; set; }
        public string fldTitleBime { get; set; }
        public string fldTypeBimeId { get; set; }
        public Nullable<int> fldkosuratBudgetPayId { get; set; }
        public int fldType { get; set; }
    }
}
