//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_RptSanad3
    {
        public long KolMotalebat { get; set; }
        public long fldMotalebat { get; set; }
        public long hoghogh { get; set; }
        public long ezafekar { get; set; }
        public long karane { get; set; }
        public long tashilatrefahi { get; set; }
        public long SanavatPayanKhedmat { get; set; }
        public long tatilkari { get; set; }
        public long ayelemandi { get; set; }
        public long khoraki { get; set; }
        public long kalaBehdashti { get; set; }
        public long Monasebat { get; set; }
        public long mamoriat { get; set; }
        public long bimeKarfarma { get; set; }
        public long darmanKarfarma { get; set; }
        public long omrKarfarma { get; set; }
        public long TakmiliKarfarma { get; set; }
        public long pasandazKarfarma { get; set; }
        public long bime { get; set; }
        public long maliat { get; set; }
        public long pasandaz { get; set; }
        public long omr { get; set; }
        public long darman { get; set; }
        public long takmili { get; set; }
        public long kolkosurat { get; set; }
        public long Khales { get; set; }
        public int fldEmploymentCenterId { get; set; }
        public string NameTypeCostCenters { get; set; }
        public int fldTypeBimeId { get; set; }
        public int fldTypeOfCostCenterId { get; set; }
        public string NameEmploymentCenter { get; set; }
    }
}
