//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDocumentRecord_DetailsSelect
    {
        public int fldId { get; set; }
        public int fldDocument_HedearId { get; set; }
        public int fldCodingId { get; set; }
        public string fldDescription { get; set; }
        public long fldBedehkar { get; set; }
        public long fldBestankar { get; set; }
        public Nullable<int> fldCenterCoId { get; set; }
        public Nullable<int> fldCaseId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public int fldUserId { get; set; }
        public int fldSourceId { get; set; }
        public int fldCaseTypeId { get; set; }
        public string fldName { get; set; }
        public string fldNameCenter { get; set; }
        public Nullable<short> fldOrder { get; set; }
        public string fldCode { get; set; }
        public string fldNameCoding { get; set; }
        public string fldName_CodeDetail { get; set; }
    }
}
