//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMoavaghatSelect
    {
        public int fldId { get; set; }
        public int fldMohasebatId { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public int fldHaghDarmanKarfFarma { get; set; }
        public int fldHaghDarmanDolat { get; set; }
        public int fldHaghDarman { get; set; }
        public int fldBimePersonal { get; set; }
        public int fldBimeKarFarma { get; set; }
        public int fldBimeBikari { get; set; }
        public int fldBimeMashaghel { get; set; }
        public int fldPasAndaz { get; set; }
        public int fldMashmolBime { get; set; }
        public int fldMashmolMaliyat { get; set; }
        public Nullable<int> fldkhalesPardakhti { get; set; }
        public int fldMaliyat { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldHokmId { get; set; }
    }
}
