//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectTashimDaramadCode
    {
        public int fldCodingAcc_DetailsId { get; set; }
        public string fldTitle { get; set; }
        public string fldCode { get; set; }
        public string fldDaramadCode { get; set; }
        public Nullable<decimal> fldPercentHazine { get; set; }
        public Nullable<decimal> fldPercentTamallok { get; set; }
        public string fldHazine { get; set; }
        public string fldSarmaye { get; set; }
        public string fldMali { get; set; }
        public string fldHozeMasraf { get; set; }
        public string fldHozeMamooriyat { get; set; }
    }
}
