//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblArze_DetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldParametrSabetCodeDaramd { get; set; }
        public string fldValue { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public bool fldFlag { get; set; }
        public string fldNameParametreEn { get; set; }
        public string fldNameParametreFa { get; set; }
        public string fldValue_Arze { get; set; }
    }
}
