//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectChartEjraee_LastNode
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public Nullable<int> fldPId { get; set; }
        public Nullable<int> fldOrganId { get; set; }
        public byte fldNoeVahed { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNoeVahedName { get; set; }
        public string fldOrganizationName { get; set; }
        public string fldNameFather { get; set; }
    }
}
