//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblShomareHesabPasAndazSelect
    {
        public int fldId { get; set; }
        public int fldPersonalId { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldBankName { get; set; }
        public string fldName { get; set; }
        public int fldBankFixId { get; set; }
        public int fldShomareHesabPersonalId { get; set; }
        public Nullable<int> fldShomareHesabKarfarmaId { get; set; }
        public string fldShomareHesabPersonal { get; set; }
        public string fldShomareHesabKarfarma { get; set; }
    }
}
