//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBime
    {
        public int fldid { get; set; }
        public Nullable<int> fldAnvaEstekhdamId { get; set; }
        public decimal fldDarsadBimeKarFarma { get; set; }
        public decimal fldDarsadBimePersonal { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string fldJobeCode { get; set; }
        public string fldJobDesc { get; set; }
        public int fldKarkard { get; set; }
        public string fldCodemeli { get; set; }
        public string fldShomareBime { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldTarikhEstekhdam { get; set; }
        public Nullable<int> fldNoeEstekhdamId { get; set; }
        public string fldTarikhTavalod { get; set; }
        public bool fldMeliyat { get; set; }
        public bool fldJensiyat { get; set; }
        public string NameSodoor { get; set; }
        public int fldPayeSanavati { get; set; }
        public int fldTaahol { get; set; }
        public Nullable<long> fldBimePersonal { get; set; }
        public Nullable<long> fldBimeKarFarma { get; set; }
        public Nullable<long> fldMashmolBime { get; set; }
        public Nullable<long> fldBimeBikari { get; set; }
        public Nullable<long> fldItem { get; set; }
        public Nullable<long> KargariMahane { get; set; }
        public Nullable<long> KarmandiMahane { get; set; }
        public string fldSh_Personali { get; set; }
    }
}
