//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_selectAccountingTypeLevel
    {
        public int fldId { get; set; }
        public int fldAccountTypeId { get; set; }
        public int fldArghumNum { get; set; }
        public string fldName { get; set; }
    }
}
