//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblPersonalStatusSelect
    {
        public int fldId { get; set; }
        public int fldStatusId { get; set; }
        public Nullable<int> fldPrsPersonalInfoId { get; set; }
        public Nullable<int> fldPayPersonalInfoId { get; set; }
        public string fldDateTaghirVaziyat { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldTitle { get; set; }
    }
}
