//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCodhayeDaramdSelect
    {
        public int fldId { get; set; }
        public string fldDaramadCode { get; set; }
        public string fldDaramadTitle { get; set; }
        public bool fldMashmooleArzesheAfzoode { get; set; }
        public bool fldMashmooleKarmozd { get; set; }
        public int fldUnitId { get; set; }
        public Nullable<short> fldLevel { get; set; }
        public string fldStrhid { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameVahed { get; set; }
        public int fldFlag { get; set; }
        public int lastNod { get; set; }
        public bool fldAmuzeshParvaresh { get; set; }
    }
}
