//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblTakhfifSelect
    {
        public int fldId { get; set; }
        public string fldShomareMojavez { get; set; }
        public string fldTarikhMojavez { get; set; }
        public string fldAzTarikh { get; set; }
        public string fldTaTarikh { get; set; }
        public Nullable<decimal> fldTakhfifKoli { get; set; }
        public Nullable<decimal> fldTakhfifNaghdi { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
