//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblWebServiceLogSelect
    {
        public int fldId { get; set; }
        public string fldMatn { get; set; }
        public string fldUser { get; set; }
        public Nullable<System.DateTime> flddate { get; set; }
    }
}
