//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblHistoryLetterSelect
    {
        public int fldId { get; set; }
        public long fldCurrentLetter_Id { get; set; }
        public int fldHistoryType_Id { get; set; }
        public long fldHistoryLetter_Id { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldSubject { get; set; }
        public string fldLetterNumber { get; set; }
        public long fldCreatedLetterId { get; set; }
        public string fldLetterDate { get; set; }
        public int fldComisionID { get; set; }
        public string fldHistoryTypeName { get; set; }
    }
}
