//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKosorateParametri_PersonalSelect
    {
        public int fldId { get; set; }
        public int fldPersonalId { get; set; }
        public int fldParametrId { get; set; }
        public bool fldNoePardakht { get; set; }
        public int fldMablagh { get; set; }
        public int fldTedad { get; set; }
        public string fldTarikhePardakht { get; set; }
        public bool fldSumFish { get; set; }
        public bool fldMondeFish { get; set; }
        public int fldSumPardakhtiGHabl { get; set; }
        public int fldMondeGHabl { get; set; }
        public bool fldStatus { get; set; }
        public int fldDateDeactive { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNoePardakhtName { get; set; }
        public string fldstatusName { get; set; }
        public string fldSh_Personali { get; set; }
        public string fldName_Father { get; set; }
        public string fldCodemeli { get; set; }
        public string fldParamTitle { get; set; }
    }
}
