//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCodingTarh_KhedmatSelect
    {
        public int fldId { get; set; }
        public int fldCodingBudjeId { get; set; }
        public int fldEtebarTypeId { get; set; }
        public int fldTypeMasrafId { get; set; }
        public int fldOrganId { get; set; }
        public string fldAddress { get; set; }
        public Nullable<int> fldHoghoghiId { get; set; }
        public Nullable<int> fldHaghighiId { get; set; }
        public short fldStartYear { get; set; }
        public short fldEndYear { get; set; }
        public int fldValue { get; set; }
        public long fldPriceVahed { get; set; }
        public long fldKolEtebar { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldTitleEtebar { get; set; }
        public string fldTitleMasraf { get; set; }
        public string NameOperator { get; set; }
    }
}
