//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCoding_ProjeFaaliatSelect
    {
        public int fldId { get; set; }
        public int fldCodingDetailId { get; set; }
        public string fldCodingTitle { get; set; }
        public Nullable<int> fldMahiyatId { get; set; }
        public string fldCodeAcc { get; set; }
    }
}
