//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblVadiSalamSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public int fldStateId { get; set; }
        public int fldCityId { get; set; }
        public string fldAddress { get; set; }
        public string fldLatitude { get; set; }
        public string fldLongitude { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldIP { get; set; }
        public string fldNameState { get; set; }
        public string fldNameCity { get; set; }
        public int fldOrganId { get; set; }
    }
}
