//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblAssignmentSelect
    {
        public int fldID { get; set; }
        public Nullable<long> fldLetterID { get; set; }
        public Nullable<int> fldMessageId { get; set; }
        public string fldAssignmentDate { get; set; }
        public string fldAnswerDate { get; set; }
        public Nullable<int> fldSourceAssId { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public int fldOrganId { get; set; }
        public string fldIP { get; set; }
        public string fldTitleMessage { get; set; }
        public string fldSubject { get; set; }
    }
}
