//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_RptKosurBazneshastegi
    {
        public int fldHoghogh { get; set; }
        public int fldfoghjazb { get; set; }
        public int fldNobatKari { get; set; }
        public int fldSakhtikar { get; set; }
        public int fldfoghshoghl { get; set; }
        public int fldKosur { get; set; }
        public int fldHoghoghMoavaghe { get; set; }
        public int fldfoghjazbMoavaghe { get; set; }
        public int fldNobatKariMoavaghe { get; set; }
        public int fldSakhtikarMoavaghe { get; set; }
        public int fldfoghshoghlMoavaghe { get; set; }
        public int KosurMoavaghe { get; set; }
        public int fldMazad30sal { get; set; }
        public int fldMazad30salMoavaghe { get; set; }
        public int MogharariMahAval { get; set; }
        public int Mogharari { get; set; }
        public int fldpersonalId { get; set; }
        public int SahamKarmand { get; set; }
        public int SahmKarfarma { get; set; }
        public int SahamKarmandMoavaghe { get; set; }
        public int SahmKarfarmaMoavaghe { get; set; }
    }
}
