//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblItemsHoghughiSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public string fldNameEN { get; set; }
        public byte fldType { get; set; }
        public Nullable<byte> fldTypeHesabId { get; set; }
        public string fldTitleHesab { get; set; }
        public Nullable<byte> fldMostamar { get; set; }
        public string fldMostamarName { get; set; }
    }
}
