//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblProject_DetailsSelect
    {
        public int fldId { get; set; }
        public string fldAddress { get; set; }
        public string fldMojri { get; set; }
        public short fldStratYear { get; set; }
        public short fldEndYear { get; set; }
        public int fldMeghdar { get; set; }
        public long fldGheymatVahed { get; set; }
        public long fldEtebar { get; set; }
        public int fldOrganId { get; set; }
        public System.DateTime flddate { get; set; }
        public string fldDesc { get; set; }
        public int fldUserId { get; set; }
        public int fldProject_faaliyatId { get; set; }
        public short fldYear { get; set; }
    }
}
