//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblGeneralSettingSelect
    {
        public byte fldId { get; set; }
        public string fldName { get; set; }
        public string fldValue { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldOrganId { get; set; }
        public Nullable<int> fldModuleId { get; set; }
        public string fldNameModule { get; set; }
        public string fldTitleCombo { get; set; }
    }
}
