//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKomakGheyerNaghdiGroupSelect
    {
        public int fldPersonalInfoId { get; set; }
        public string fldName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public int fldId { get; set; }
        public int fldShomareHesabId { get; set; }
        public bool fldNoeMostamer { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public int fldMablagh { get; set; }
        public int fldKhalesPardakhti { get; set; }
        public int fldMaliyat { get; set; }
        public string fldShomareHesab { get; set; }
        public string fldNoeMostamerName { get; set; }
    }
}
