//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblParametreSabetSelect
    {
        public int fldId { get; set; }
        public string fldNameParametreFa { get; set; }
        public string fldNameParametreEn { get; set; }
        public bool fldNoe { get; set; }
        public byte fldNoeField { get; set; }
        public bool fldVaziyat { get; set; }
        public Nullable<int> fldComboBaxId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string NoeName { get; set; }
        public string NoeFieldName { get; set; }
        public string fldDaramadTitle { get; set; }
        public string VaziyatName { get; set; }
        public string fldTitle { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public int fldShomareHesabCodeDaramadId { get; set; }
        public bool fldTypeParametr { get; set; }
        public string fldNoeParametr { get; set; }
    }
}
