//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectTimeLine
    {
        public string fldTitleKartabl { get; set; }
        public string fldTitleAction { get; set; }
        public string fldName_familyUser { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
    }
}
