//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCostCenterSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public int fldReportTypeId { get; set; }
        public int fldTypeOfCostCenterId { get; set; }
        public int fldEmploymentCenterId { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldReportTypeName { get; set; }
        public string EmploymentName { get; set; }
        public string TypecenterTitle { get; set; }
        public Nullable<int> fldorganid { get; set; }
    }
}
