//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_LastNum_AtfDocumentRecord
    {
        public int fldDocumentNum { get; set; }
        public int AtfNum { get; set; }
        public int ShomareRoozane { get; set; }
    }
}
