//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectAshkhas_ElamAvarez
    {
        public int fldId { get; set; }
        public bool fldType { get; set; }
        public string fldTarikh { get; set; }
        public int fldOrganId { get; set; }
        public long fldMablaghKoli { get; set; }
        public long fldMablaghTakhfif { get; set; }
        public long fldMablaghGHabelPardakht { get; set; }
        public string fldNameOrgan { get; set; }
        public string SharhDesc { get; set; }
        public string Noe { get; set; }
        public int FishId { get; set; }
        public int ReplyId { get; set; }
        public string fldDesc { get; set; }
    }
}
