//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblShomareSelect
    {
        public int fldId { get; set; }
        public int fldRadifId { get; set; }
        public string fldShomare { get; set; }
        public byte fldTedadTabaghat { get; set; }
        public int fldUserId { get; set; }
        public string fldIp { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameRadif { get; set; }
        public int fldOrganId { get; set; }
    }
}
