//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMorakhasiGroupSelect
    {
        public int fldPersonalInfoId { get; set; }
        public string fldName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public int fldMorakhasiId { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public int fldTedad { get; set; }
        public short fldSalAkharinHokm { get; set; }
        public byte fldNobatePardakht { get; set; }
        public Nullable<bool> fldChecked { get; set; }
    }
}
