//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblProgramSettingSelect
    {
        public int fldID { get; set; }
        public string fldEmailAddress { get; set; }
        public string fldEmailPassword { get; set; }
        public string fldRecieveServer { get; set; }
        public string fldSendServer { get; set; }
        public int fldSendPort { get; set; }
        public bool fldSSL { get; set; }
        public bool fldDelFax { get; set; }
        public bool fldIsSigner { get; set; }
        public string fldFaxPath { get; set; }
        public int fldOrganID { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldIP { get; set; }
        public int fldRecievePort { get; set; }
        public string NameOrgan { get; set; }
    }
}
