//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblEzafeKari_TatilKariGroupSelect
    {
        public int fldPersonalInfoId { get; set; }
        public string fldName_Father { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public int fldPrs_PersonalInfoId { get; set; }
        public int fldEzafeKari_TatilKariId { get; set; }
        public short fldYear { get; set; }
        public byte fldMonth { get; set; }
        public byte fldNobatePardakht { get; set; }
        public decimal fldCount { get; set; }
        public bool fldHasBime { get; set; }
        public bool fldHasMaliyat { get; set; }
        public Nullable<bool> fldChecked { get; set; }
        public Nullable<int> fldTypeEstekhdamId { get; set; }
    }
}
