//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBime_Tatilkar_Ezafekar
    {
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string fldJobeCode { get; set; }
        public string fldJobDesc { get; set; }
        public string fldCodemeli { get; set; }
        public string fldShomareBime { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldTarikhEstekhdam { get; set; }
        public Nullable<int> fldNoeEstekhdamId { get; set; }
        public string fldTarikhTavalod { get; set; }
        public bool fldMeliyat { get; set; }
        public bool fldJensiyat { get; set; }
        public string NameSodoor { get; set; }
        public int PersonalId { get; set; }
        public int fldMashmolBime { get; set; }
        public int fldMablagh { get; set; }
        public int fldBimePersonal { get; set; }
        public int fldBimeKarFarma { get; set; }
        public int fldBimeBikari { get; set; }
        public string fldSh_Personali { get; set; }
    }
}
