//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_TreeOrganPostEjra
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> pid { get; set; }
        public string title { get; set; }
        public string Namechart { get; set; }
        public string fldOrgPostCode { get; set; }
    }
}
