//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketSina
    {
        public string fldCodemeli { get; set; }
        public int fldSathPost { get; set; }
        public string OrganPost { get; set; }
        public Nullable<int> fldTypeEstekhdamSina { get; set; }
        public Nullable<int> fldMadrakId { get; set; }
        public Nullable<byte> fldGroup { get; set; }
        public byte fldMoreGroup { get; set; }
        public Nullable<int> s_rasmi { get; set; }
        public string fldTabaghe { get; set; }
        public Nullable<int> fldBimePersonalTamin { get; set; }
        public Nullable<int> fldBimePersonalDarman { get; set; }
        public Nullable<int> fldSandoghBazneshastegi { get; set; }
        public int fldMogharari { get; set; }
        public Nullable<int> fldBimeKarFarma { get; set; }
        public int h_paye { get; set; }
        public int sanavat { get; set; }
        public int paye { get; set; }
        public int sanavat_basiji { get; set; }
        public Nullable<int> HadeghalDastmozd { get; set; }
        public int sakhtikar { get; set; }
        public int fogh_isar { get; set; }
        public int sanavat_isar { get; set; }
        public int foghshoghl { get; set; }
        public int ayelemandi { get; set; }
        public int olad { get; set; }
        public int maskan { get; set; }
        public int bon { get; set; }
        public int modiryati { get; set; }
        public Nullable<int> jazb { get; set; }
        public int khas { get; set; }
        public int abohava { get; set; }
        public int nobatkari { get; set; }
        public int ghazai { get; set; }
        public int tatbigh1 { get; set; }
        public int tatbigh { get; set; }
        public int masrafi { get; set; }
        public int tarmim { get; set; }
        public int takhasosi { get; set; }
        public Nullable<int> ezafekar { get; set; }
        public int mamoriat { get; set; }
        public int karane { get; set; }
        public int made26 { get; set; }
        public int barjastegi { get; set; }
        public int tashilat { get; set; }
        public int tadil { get; set; }
        public Nullable<int> band_y { get; set; }
        public int jazb9 { get; set; }
        public Nullable<int> makhsos { get; set; }
        public Nullable<int> vije { get; set; }
        public int eydi { get; set; }
        public int s_payankhedmat { get; set; }
        public int khoraki { get; set; }
        public int riali { get; set; }
        public int Monasebat { get; set; }
        public int javani { get; set; }
        public int mahdeKodak { get; set; }
        public int refahi { get; set; }
        public int fldBimeTakmily { get; set; }
        public int fldBimeOmr { get; set; }
        public int kalaBehdashti { get; set; }
        public int fldMablaghMoavagheHokm { get; set; }
        public int fldMaliyat { get; set; }
        public int jazb_tabsare { get; set; }
        public int talash { get; set; }
        public int jebhe { get; set; }
        public int janbazi { get; set; }
        public int sayer { get; set; }
        public int ashoora { get; set; }
        public int zaribtadil { get; set; }
        public int jazbTakhasosi { get; set; }
        public int jazbtadil { get; set; }
        public int hadaghaltadil { get; set; }
        public Nullable<long> Kosurat { get; set; }
    }
}
