//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblRemittance_HeaderSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldAshkhasiId { get; set; }
        public bool fldStatus { get; set; }
        public string fldStartDate { get; set; }
        public string fldEndDate { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldStatusName { get; set; }
        public string fldKalaName { get; set; }
        public string fldTypeShakhs { get; set; }
        public string fldFamilyName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldTitle { get; set; }
        public string fldNameChart { get; set; }
        public string fldNameAshkhas_Chart { get; set; }
        public Nullable<int> fldEmployId { get; set; }
        public Nullable<int> fldChartOrganEjraeeId { get; set; }
        public string fldNameNoeHavale { get; set; }
        public string fldNameTahvilGirande { get; set; }
        public Nullable<int> fldFileId { get; set; }
    }
}
