//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblStatusTaghsit_TakhfifSelect
    {
        public int fldId { get; set; }
        public int fldRequestId { get; set; }
        public byte fldTypeMojavez { get; set; }
        public byte fldTypeRequest { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string Vaziyat { get; set; }
        public string NoeDarkhast { get; set; }
    }
}
