//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKarkardMahane_DetailSelect
    {
        public int fldId { get; set; }
        public int fldKarkardMahaneId { get; set; }
        public int fldKarkard { get; set; }
        public int fldKargahBimeId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldWorkShopName { get; set; }
        public string fldWorkShopNum { get; set; }
        public string fldEmployerName { get; set; }
    }
}
