//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMahdoodiyatMohasebatSelect
    {
        public int fldId { get; set; }
        public string fldAzTarikh { get; set; }
        public string fldTatarikh { get; set; }
        public bool fldNoeKarbar { get; set; }
        public bool fldNoeCodeDaramad { get; set; }
        public bool fldNoeAshkhas { get; set; }
        public bool fldStatus { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNoeKarbarName { get; set; }
        public string fldNoeCodeDaramadName { get; set; }
        public string fldNoeAshkhasName { get; set; }
        public string fldStatusName { get; set; }
        public string fldTitle { get; set; }
    }
}
