//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMohasebat_MorakhasiSelect
    {
        public int fldId { get; set; }
        public int fldPersonalId { get; set; }
        public byte fldTedad { get; set; }
        public int fldMablagh { get; set; }
        public byte fldMonth { get; set; }
        public short fldYear { get; set; }
        public byte fldNobatPardakht { get; set; }
        public short fldSalHokm { get; set; }
        public int fldHokmId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
