//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKarKardeMahaneGroupSelect
    {
        public int fldPersonalInfoId { get; set; }
        public string fldName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public int fldCostCenterId { get; set; }
        public int fldOrganPostId { get; set; }
        public int fldPrs_PersonalInfoId { get; set; }
        public int fldKarKardeMahaneId { get; set; }
        public short fldyear { get; set; }
        public byte fldMah { get; set; }
        public Nullable<byte> fldKarkard { get; set; }
        public byte fldGheybat { get; set; }
        public Nullable<byte> fldNobateKari { get; set; }
        public decimal fldEzafeKari { get; set; }
        public decimal fldTatileKari { get; set; }
        public byte fldMamoriatBaBeitote { get; set; }
        public byte fldMamoriatBedoneBeitote { get; set; }
        public int fldMosaedeh { get; set; }
        public byte fldNobatePardakht { get; set; }
        public bool fldGhati { get; set; }
        public decimal fldGhatiEzafeKar { get; set; }
        public byte fldBa10 { get; set; }
        public byte fldBa20 { get; set; }
        public byte fldBa30 { get; set; }
        public byte fldBe10 { get; set; }
        public byte fldBe20 { get; set; }
        public byte fldBe30 { get; set; }
        public Nullable<bool> fldChecked { get; set; }
        public Nullable<int> fldTypeEstekhdamId { get; set; }
        public int fldShift { get; set; }
        public Nullable<bool> fldMoavaghe { get; set; }
        public string fldAzTarikhMoavagheS { get; set; }
        public string fldTaTarikhMoavagheS { get; set; }
        public Nullable<short> fldMeetingCount { get; set; }
        public Nullable<byte> fldEstelagi { get; set; }
    }
}
