//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBimeKhadamatDarmani
    {
        public byte fldKarkard { get; set; }
        public int fldHaghDarman { get; set; }
        public int fldMashmolBime { get; set; }
        public string fldTarikhEjra { get; set; }
        public Nullable<int> fldTedadBime1 { get; set; }
        public Nullable<int> fldTedadBime2 { get; set; }
        public Nullable<int> fldTedadBime3 { get; set; }
        public string fldName_Family { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public int fldMoavaghe { get; set; }
    }
}
