//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblModule_OrganSelect
    {
        public int fldId { get; set; }
        public int fldOrganId { get; set; }
        public int fldModuleId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameOrgan { get; set; }
        public string fldNameModule { get; set; }
        public string fldNameModule_Organ { get; set; }
        public int fldPermissionId { get; set; }
    }
}
