//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblParametreOmoomi_ValueSelect
    {
        public int fldId { get; set; }
        public int fldParametreOmoomiId { get; set; }
        public string fldFromDate { get; set; }
        public string fldEndDate { get; set; }
        public string fldValue { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string nameParametrFa_En { get; set; }
    }
}
