//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_RptGhabrPor_Khali
    {
        public int GheteId { get; set; }
        public int RadifId { get; set; }
        public int ShomareId { get; set; }
        public string NameGhete { get; set; }
        public string NameRadif { get; set; }
        public string Shomare { get; set; }
        public string Tabaghe { get; set; }
        public string Name_Family { get; set; }
        public string Meli_Moshakhase { get; set; }
        public string FatherName { get; set; }
        public string Sh_Sh { get; set; }
        public string TarikhFot { get; set; }
        public string NameVadiSalam { get; set; }
    }
}
