//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDaramadGroup_ParametrSelect
    {
        public int fldId { get; set; }
        public int fldDaramadGroupId { get; set; }
        public string fldEnName { get; set; }
        public string fldFnName { get; set; }
        public bool fldStatus { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldStatusName { get; set; }
        public byte fldNoeField { get; set; }
        public Nullable<int> fldComboBoxId { get; set; }
        public Nullable<int> fldFormuleId { get; set; }
        public string NoeFieldName { get; set; }
    }
}
