//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_selectEbtal_SodoorFish
    {
        public int fldId { get; set; }
        public int fldElamAvarezId { get; set; }
        public int fldItem { get; set; }
        public long fldMaliyat { get; set; }
        public long fldAvarez { get; set; }
        public long fldJamFish { get; set; }
        public string fldShenaseGhabz { get; set; }
        public string fldShenasePardakht { get; set; }
        public string fldStatus { get; set; }
        public byte fldShorooshenaseGhabz { get; set; }
        public int fldShomareHesabId { get; set; }
        public string fldShomareHesab { get; set; }
        public long fldAsliValue { get; set; }
        public int fldOrganId { get; set; }
        public long fldjamkol { get; set; }
        public long fldMablaghTakhfif { get; set; }
        public string PardakhtStatus { get; set; }
        public Nullable<long> fldAmuzeshParvareshValue { get; set; }
    }
}
