//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblReplyTaghsitSelect
    {
        public int fldId { get; set; }
        public long fldMablaghNaghdi { get; set; }
        public byte fldTedadAghsat { get; set; }
        public string fldShomareMojavez { get; set; }
        public string fldTarikh { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldStatusId { get; set; }
        public byte fldTedadMahAghsat { get; set; }
        public long fldJarimeTakhir { get; set; }
        public Nullable<decimal> fldDarsad { get; set; }
        public string fldDescKarmozd { get; set; }
    }
}
