//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblHistoryTahsilatSelect
    {
        public int fldId { get; set; }
        public int fldEmployeeId { get; set; }
        public int fldMadrakId { get; set; }
        public int fldReshteId { get; set; }
        public string fldTarikh { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTitleMadrak { get; set; }
        public string fldTitleReshte { get; set; }
    }
}
