//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblItemNecessarySelect
    {
        public int fldId { get; set; }
        public string fldNameItem { get; set; }
        public int fldMahiyatId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIp { get; set; }
        public int fldUserId { get; set; }
        public byte fldTypeHesabId { get; set; }
        public string fldNameTypeHesab { get; set; }
        public Nullable<int> fldMahiyat_GardeshId { get; set; }
    }
}
