//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_SelectPayPersonalInfo_Ezafekar
    {
        public int fldId { get; set; }
        public int fldPrs_PersonalInfoId { get; set; }
        public int fldTypeBimeId { get; set; }
        public string fldShomareBime { get; set; }
        public bool fldBimeOmr { get; set; }
        public bool fldBimeTakmili { get; set; }
        public bool fldMashagheleSakhtVaZianAvar { get; set; }
        public int fldCostCenterId { get; set; }
        public bool fldMazad30Sal { get; set; }
        public bool fldPasAndaz { get; set; }
        public bool fldSanavatPayanKhedmat { get; set; }
        public int fldInsuranceWorkShopId { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldName { get; set; }
        public string fldFatherName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Personali { get; set; }
        public string fldTitleTypeBime { get; set; }
        public string fldWorkShopName { get; set; }
        public string fldJobDesc { get; set; }
        public string fldJobeCode { get; set; }
        public string fldBimeOmrName { get; set; }
        public string fldBimeTakmiliName { get; set; }
        public string fldMashagheleSakhtVaZianAvarName { get; set; }
        public string fldMazadCSalName { get; set; }
        public string fldPasAndazName { get; set; }
        public string fldSanavatPayanKhedmatName { get; set; }
        public string fldTitleCostCenter { get; set; }
        public string fldName_Father { get; set; }
        public bool fldHamsarKarmand { get; set; }
        public bool fldMoafDarman { get; set; }
        public string UserName { get; set; }
        public int fldEsargariId { get; set; }
        public decimal fldEzafeKari { get; set; }
        public bool fldGhati { get; set; }
    }
}
