//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblRoneveshtSelect
    {
        public int fldid { get; set; }
        public long fldLetterId { get; set; }
        public Nullable<int> fldCommisionId { get; set; }
        public string fldAssignmentTypeId { get; set; }
        public string fldText { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldName { get; set; }
        public string fldId_Type { get; set; }
        public Nullable<int> fldAshkhasHoghoghiTitlesId { get; set; }
    }
}
