//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblBankBill_DetailsSelect
    {
        public int fldId { get; set; }
        public int fldHedearId { get; set; }
        public long fldBedehkar { get; set; }
        public long fldBestankar { get; set; }
        public long fldMandeh { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public string fldCodePeygiri { get; set; }
    }
}
