//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_SelectVariziForBank
    {
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public Nullable<long> fldkhalesPardakhti { get; set; }
        public string fldShomareHesab { get; set; }
        public string fldCodemeli { get; set; }
        public string fldAddress { get; set; }
        public Nullable<byte> fldMaliyatEsargari { get; set; }
        public int fldEsargariId { get; set; }
        public string fldTarikhEstekhdam { get; set; }
        public string fldCodePosti { get; set; }
        public string fldShomareBime { get; set; }
        public Nullable<int> fldMadrakId { get; set; }
        public string fldRasteShoghli { get; set; }
        public int fldTypeBimeId { get; set; }
        public Nullable<bool> fldMeliyat { get; set; }
        public string MahalKhedmat { get; set; }
        public string Semat { get; set; }
        public Nullable<int> fldMaliyat { get; set; }
        public Nullable<int> fldNoeEstekhdam { get; set; }
        public int fldPersonalId { get; set; }
        public int fldPayPersonalId { get; set; }
        public int fldMablagh { get; set; }
    }
}
