//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_DisketBime_DBF
    {
        public string Dsw_ID { get; set; }
        public string fldShomareBime { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string NameSodoor { get; set; }
        public string fldTarikhTavalod { get; set; }
        public string fldJensiyatName { get; set; }
        public string fldMeliyatName { get; set; }
        public string fldJobDesc { get; set; }
        public string Dsw_SDate { get; set; }
        public string Dsw_EDate { get; set; }
        public int Dsw_IDate { get; set; }
        public int fldKarkard { get; set; }
        public Nullable<long> fldRozane { get; set; }
        public Nullable<int> fldPayeSanavati { get; set; }
        public Nullable<long> fldMazayaMahiyane { get; set; }
        public Nullable<long> fldMashmolBime { get; set; }
        public Nullable<long> fldItem { get; set; }
        public Nullable<long> fldBimePersonal { get; set; }
        public string fldJobeCode { get; set; }
        public Nullable<int> fldTaahol { get; set; }
        public Nullable<long> fldMahane { get; set; }
        public string fldCodemeli { get; set; }
        public int DSW_PRATE { get; set; }
    }
}
