//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblEmployee_DetailSelect
    {
        public int fldId { get; set; }
        public int fldEmployeeId { get; set; }
        public string fldFatherName { get; set; }
        public Nullable<bool> fldJensiyat { get; set; }
        public Nullable<int> fldMadrakId { get; set; }
        public Nullable<byte> fldNezamVazifeId { get; set; }
        public Nullable<int> fldTaaholId { get; set; }
        public Nullable<int> fldReshteId { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldSh_Shenasname { get; set; }
        public Nullable<int> fldMahalTavalodId { get; set; }
        public Nullable<int> fldMahalSodoorId { get; set; }
        public string fldTarikhSodoor { get; set; }
        public string fldAddress { get; set; }
        public string fldCodePosti { get; set; }
        public Nullable<bool> fldMeliyat { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodemeli { get; set; }
        public string fldTarikhTavalod { get; set; }
        public byte fldTypeShakhs { get; set; }
        public string fldTypeShakhsName { get; set; }
        public string fldTel { get; set; }
        public string fldMobile { get; set; }
    }
}
