//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMasuolin_DetailSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldEmployId { get; set; }
        public Nullable<int> fldOrganPostId { get; set; }
        public int fldMasuolinId { get; set; }
        public int fldOrderId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTarikhEjra { get; set; }
        public int fldModule_OrganId { get; set; }
        public string fldNameEmployee { get; set; }
        public string fldNameOrgan { get; set; }
        public string NamePostOrgan { get; set; }
        public string TitlePost { get; set; }
    }
}
