//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectForEmalTakhfif
    {
        public int fldID { get; set; }
        public int fldTedad { get; set; }
        public Nullable<long> AsliValue { get; set; }
        public Nullable<long> fldTakhfifAsliValue { get; set; }
        public string fldSharheCodeDaramad { get; set; }
        public string fldDaramadCode { get; set; }
    }
}
