//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblShomareHesab_FormulaSelect
    {
        public int fldId { get; set; }
        public int fldShomareHesab_CodeId { get; set; }
        public string fldFormolsaz { get; set; }
        public Nullable<int> fldFormulKoliId { get; set; }
        public Nullable<int> fldFormulMohasebatId { get; set; }
        public string fldTarikhEjra { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserId { get; set; }
    }
}
