//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblAfradeTahtePoshesheBimeTakmily_DetailsSelect
    {
        public int fldId { get; set; }
        public int fldAfradTahtePoshehsId { get; set; }
        public int fldBimeTakmiliId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldPersonalId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldBirthDate { get; set; }
        public string fldCodeMeli { get; set; }
        public Nullable<int> fldAge { get; set; }
        public int fldBedonePoshesh { get; set; }
        public string fldBedonePosheshName { get; set; }
        public string fldNameNesbatShakhs { get; set; }
    }
}
