//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblBudje_khedmatDarsadIdSelect
    {
        public int fldBudje_khedmatDarsadId { get; set; }
        public int fldCodingAcc_detailId { get; set; }
        public int fldCodingBudje_DetailsId { get; set; }
        public double fldDarsad { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserId { get; set; }
        public string fldTitleAcc { get; set; }
        public string fldCodeAcc { get; set; }
        public string fldTitleBudje { get; set; }
        public string fldCodeBudje { get; set; }
    }
}
