//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_RptDafater
    {
        public string fldCode { get; set; }
        public string fldTitle { get; set; }
        public Nullable<long> fldBedehkar { get; set; }
        public Nullable<long> fldBestankar { get; set; }
        public int fldDocumentNum { get; set; }
        public string fldTarikhDocument { get; set; }
        public string fldDescriptionDocu { get; set; }
        public Nullable<long> fldMande { get; set; }
    }
}
