//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_RptKosuratBank
    {
        public int fldId { get; set; }
        public string fldNameBank { get; set; }
        public Nullable<int> fldMablagh { get; set; }
        public int fldShobeId { get; set; }
        public short fldYear { get; set; }
        public string fldMonth { get; set; }
        public string fldShomareHesab { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public int fldBankId { get; set; }
        public string fldDesc { get; set; }
        public string fldFatherName { get; set; }
    }
}
