//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblPardakhtFishSelect
    {
        public int fldId { get; set; }
        public int fldFishId { get; set; }
        public System.DateTime fldDatePardakht { get; set; }
        public int fldNahvePardakhtId { get; set; }
        public string fldTarikh { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldPardakhtFiles_DetailId { get; set; }
        public Nullable<System.DateTime> fldDateVariz { get; set; }
        public string fldTarikhVariz { get; set; }
    }
}
