//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectDocumentEkhtetamiye
    {
        public int fldCodingId { get; set; }
        public string fldTitle { get; set; }
        public string fldDescription { get; set; }
        public long fldBestankar { get; set; }
        public long fldBedehkar { get; set; }
        public int fldCenterCoId { get; set; }
        public int fldCaseId { get; set; }
        public string fldName_CodeDetail { get; set; }
        public int fldCaseTypeId { get; set; }
        public int fldSourceId { get; set; }
        public string fldName { get; set; }
    }
}
