//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblTozinSelect
    {
        public int fldId { get; set; }
        public int fldWeighbridgeId { get; set; }
        public int fldMaxW { get; set; }
        public Nullable<int> fldPlaqueId { get; set; }
        public System.DateTime fldHour { get; set; }
        public System.DateTime fldStartDate { get; set; }
        public System.DateTime fldEndDate { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldPlaque { get; set; }
        public string fldNameBaskool { get; set; }
        public string fldTarikhShoroo { get; set; }
        public string fldTarikhPayan { get; set; }
        public string fldSaat { get; set; }
    }
}
