//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMotevaffaSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldCauseOfDeathId { get; set; }
        public int fldGhabreAmanatId { get; set; }
        public string fldTarikhFot { get; set; }
        public string fldTarikhDafn { get; set; }
        public int fldOrganId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public Nullable<int> fldMahalFotId { get; set; }
        public string fldNameMahal { get; set; }
        public string fldReason { get; set; }
        public string fldname { get; set; }
        public string fldFamily { get; set; }
        public string fldShomare { get; set; }
        public string fldFatherName { get; set; }
        public string fldCodemeli { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldCodeMoshakhase { get; set; }
        public Nullable<int> fldGheteId { get; set; }
        public Nullable<int> fldRadifId { get; set; }
        public Nullable<int> fldVadiSalamId { get; set; }
        public string fldNameVadiSalam { get; set; }
        public string fldNameGhete { get; set; }
        public string fldNameRadif { get; set; }
        public string fldTypeNameMotevafa { get; set; }
        public int fldTypeMotevafa { get; set; }
        public int fldShomareId { get; set; }
        public string fldCodeMotevafa { get; set; }
        public byte fldTabaghe { get; set; }
    }
}
