//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCaseBillsSelect
    {
        public int fldId { get; set; }
        public int fldBillsTypeId { get; set; }
        public int fldFileNum { get; set; }
        public int fldCentercoId { get; set; }
        public int fldOrganId { get; set; }
        public int fldOrganChartId { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public int fldUserId { get; set; }
        public string fldName_BillsType { get; set; }
        public string fldNameCenter { get; set; }
        public string fldName_shakhs { get; set; }
        public string fldCodeMelli { get; set; }
        public string fldTitle_chartOrgan { get; set; }
        public string fldName_Organ { get; set; }
        public string fldShakhs_Type { get; set; }
    }
}
