//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblItemsEstekhdam_FiscalTitleSelect
    {
        public int fldId { get; set; }
        public int fldItemsHoghughiId { get; set; }
        public int fldTypeEstekhdamId { get; set; }
        public string fldTitle { get; set; }
        public bool fldHasZarib { get; set; }
        public string fldHasZaribName { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldTitleItemsHoghughi { get; set; }
        public int flAnvaEstekhdamId { get; set; }
        public string fldAnvaEstekhdamTitle { get; set; }
        public Nullable<bool> fldMashmul { get; set; }
        public string fldNameDefaultTax { get; set; }
        public Nullable<bool> fldMashmoolDefaultTax { get; set; }
    }
}
