//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblSodoorFishSelect
    {
        public int fldId { get; set; }
        public int fldElamAvarezId { get; set; }
        public int fldShomareHesabId { get; set; }
        public string fldShenaseGhabz { get; set; }
        public long fldMablaghAvarezGerdShode { get; set; }
        public byte fldShorooShenaseGhabz { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldShenasePardakht { get; set; }
        public string fldStatusName { get; set; }
        public string fldStatusId { get; set; }
        public long fldJamKol { get; set; }
        public string fldBarcode { get; set; }
        public bool fldSendToMaliFlag { get; set; }
        public bool fldFishSentFlag { get; set; }
        public Nullable<System.DateTime> fldDateSendToMali { get; set; }
        public Nullable<System.DateTime> fldDateFishSent { get; set; }
    }
}
