//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMonasebatHeaderSelect
    {
        public int fldId { get; set; }
        public int fldActiveDate { get; set; }
        public Nullable<int> fldDeactiveDate { get; set; }
        public bool fldActive { get; set; }
        public string fldIP { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldActiveName { get; set; }
    }
}
