//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblDocumentRecord_HeaderSelect
    {
        public int fldId { get; set; }
        public int fldDocumentNum { get; set; }
        public Nullable<int> fldAtfNum { get; set; }
        public string fldArchiveNum { get; set; }
        public string fldDescriptionDocu { get; set; }
        public int fldOrganId { get; set; }
        public string fldTarikhDocument { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public int fldUserId { get; set; }
        public byte fldAccept { get; set; }
        public byte fldType { get; set; }
        public string fldTypeName { get; set; }
        public Nullable<int> ShomareRoozane { get; set; }
        public Nullable<int> fldShomareFaree { get; set; }
        public short fldYear { get; set; }
        public Nullable<int> fldFiscalYearId { get; set; }
        public Nullable<int> fldTypeSanad { get; set; }
        public string fldTypeSanadName { get; set; }
        public string fldNameModule { get; set; }
        public Nullable<int> fldModuleErsalId { get; set; }
        public bool fldIsArchive { get; set; }
        public Nullable<int> fldDocumentNum_Pid { get; set; }
        public int fldPId { get; set; }
        public string fldTypeSanadName_Pid { get; set; }
        public Nullable<int> fldMainDocNum { get; set; }
        public int fldFlag { get; set; }
        public byte fldIsMap { get; set; }
        public Nullable<byte> fldEdit { get; set; }
        public Nullable<int> fldCaseTypeId { get; set; }
    }
}
