//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCheckStatusSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldSodorCheckId { get; set; }
        public Nullable<int> fldCheckVaredeId { get; set; }
        public Nullable<int> fldAghsatId { get; set; }
        public byte fldvaziat { get; set; }
        public string fldTarikh { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
