//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblCodhayeDaramadiElamAvarezSelect
    {
        public int fldID { get; set; }
        public int fldElamAvarezId { get; set; }
        public string fldSharheCodeDaramad { get; set; }
        public long fldAsliValue { get; set; }
        public long fldAvarezValue { get; set; }
        public long fldMaliyatValue { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldShomareHesabId { get; set; }
        public string codeDaramadTitle { get; set; }
        public int fldTedad { get; set; }
        public int fldShomareHesabCodeDaramadId { get; set; }
        public string fldDaramadTitle { get; set; }
        public string fldDaramadCode { get; set; }
        public byte fldShorooshenaseGhabz { get; set; }
        public Nullable<long> fldSumMablgh { get; set; }
        public Nullable<long> fldTakhfifAsliValue { get; set; }
        public long fldTakhfifAvarezValue { get; set; }
        public long fldTakhfifMaliyatValue { get; set; }
        public long fldAmuzeshParvareshValue { get; set; }
        public Nullable<long> fldTakhfifAmuzeshParvareshValue { get; set; }
    }
}
