//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_MaxPersonalEstekhdamType
    {
        public int fldAnvaeEstekhdamId { get; set; }
        public string fldTitle { get; set; }
        public int fldNoeEstekhdamId { get; set; }
        public string fldTarikh { get; set; }
    }
}
