//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_RptByCoding
    {
        public Nullable<long> fldBedehkar { get; set; }
        public Nullable<long> fldBestankar { get; set; }
        public Nullable<long> MandehHeasb { get; set; }
        public Nullable<long> GardeshHesab { get; set; }
        public string fldTitle { get; set; }
        public int fldType { get; set; }
    }
}
