//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_DisketPasAndaz
    {
        public Nullable<int> fldPasAndaz { get; set; }
        public string fldShPasAndazPersonal { get; set; }
        public string fldShPasAndazKarFarma { get; set; }
        public Nullable<int> fldNoeEstekhdam { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string fldCodemeli { get; set; }
    }
}
