//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblBudgetPayDetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldTypeEstekhdamId { get; set; }
        public int fldTypeBimeId { get; set; }
        public string fldTitleEstekhdam { get; set; }
        public string fldTitleBime { get; set; }
    }
}
