//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblElamAvarezSelect
    {
        public int fldId { get; set; }
        public int fldAshakhasID { get; set; }
        public bool fldType { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string Noe { get; set; }
        public string fldNameShakhs { get; set; }
        public string fldShenaseMeli { get; set; }
        public string fldNoeShakhs { get; set; }
        public string fldTarikh { get; set; }
        public string fldFather_Sabt { get; set; }
        public int fldOrganId { get; set; }
        public int fldReplyTaghsitId { get; set; }
        public long fldMablaghKoli { get; set; }
        public long fldMablaghTakhfif { get; set; }
        public long fldMablaghGHabelPardakht { get; set; }
        public string fldStatusFish { get; set; }
        public string fldStatusTakhfif { get; set; }
        public string fldStatusTaghsit { get; set; }
        public string fldStatusFishName { get; set; }
        public string fldStatusTakhfifName { get; set; }
        public string fldStatusTaghsitName { get; set; }
        public string fldStatusKoli { get; set; }
        public string fldStatusKoliName { get; set; }
        public string fldNameOrgan { get; set; }
        public string SharhDesc { get; set; }
        public Nullable<bool> fldIsExternal { get; set; }
        public Nullable<int> fldDaramadGroupId { get; set; }
        public string fldCodeSystemMabda { get; set; }
        public string fldmobile { get; set; }
    }
}
