//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_Pay_SelectDisketMaliyatForHoghogh
    {
        public int MaliyatMoavaghe { get; set; }
        public int MashmolMaliyatMoavaghe { get; set; }
        public int MashmolMaliyatMoavagheGHeirMostamar { get; set; }
        public int MaliyatManfi { get; set; }
        public int KolMotalebat { get; set; }
        public int ItemEstekhdam { get; set; }
        public int fldMashmolMaliyat { get; set; }
        public int fldMaliyat { get; set; }
        public int fldMaliyatDaraei { get; set; }
        public int fldFiscalHeaderId { get; set; }
        public Nullable<int> ezafekar { get; set; }
        public int eydi { get; set; }
        public Nullable<int> mamoriat { get; set; }
        public Nullable<int> tatilkari { get; set; }
        public int s_payankhedmat { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodemeli { get; set; }
        public string fldFatherName { get; set; }
        public Nullable<byte> fldMaliyatEsargari { get; set; }
        public int fldEsargariId { get; set; }
        public string fldAddress { get; set; }
        public string fldTarikhEstekhdam { get; set; }
        public string fldCodePosti { get; set; }
        public string fldShomareBime { get; set; }
        public int fldTypeBimeId { get; set; }
        public Nullable<bool> fldMeliyat { get; set; }
        public string MahalKhedmat { get; set; }
        public string Semat { get; set; }
        public Nullable<int> fldNoeEstekhdam { get; set; }
        public int fldPersonalId { get; set; }
        public Nullable<int> fldMadrakId { get; set; }
        public int fldBimePersonal { get; set; }
        public int SayerMoafiyat { get; set; }
        public int karane { get; set; }
        public int fldBimeOmrPersonal { get; set; }
        public Nullable<long> fldkhalesPardakhti { get; set; }
        public Nullable<int> fldBonMostamar { get; set; }
        public Nullable<int> fldBonGheyrMostamar { get; set; }
        public int fldBonMostamarMoavagh { get; set; }
        public int fldBonGheyrMostamarMoavagh { get; set; }
        public int fldMablagh_Ezafekar { get; set; }
        public int fldKhalesPardakhti_Ezafekar { get; set; }
        public int fldMablagh_Tatilkar { get; set; }
        public int fldKhalesPardakhti_Tatilkar { get; set; }
        public int fldMablagh_komakMostamar { get; set; }
        public int fldKhalesPardakhti_komakMostamar { get; set; }
        public int fldMablagh_komakGheirMostamar { get; set; }
        public int fldKhalesPardakhti_komakGheirMostamar { get; set; }
        public int fldMablagh_Sayer { get; set; }
        public int fldKhalesPardakhti_Sayer { get; set; }
        public int fldMablagh_Mamoriat { get; set; }
        public int fldKhalesPardakhti_Mamoriat { get; set; }
        public int fldMazayaRefahi_Angizeshi { get; set; }
    }
}
