//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblMohasebat_kosorat_MotalebatParamSelect
    {
        public int fldId { get; set; }
        public int fldMohasebatId { get; set; }
        public Nullable<int> fldKosoratId { get; set; }
        public Nullable<int> fldMotalebatId { get; set; }
        public int fldMablagh { get; set; }
        public int fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
    }
}
