//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_tblKartablSelect
    {
        public int fldId { get; set; }
        public string fldTitleKartabl { get; set; }
        public int fldUserId { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldOrganId { get; set; }
        public Nullable<int> fldorderid { get; set; }
        public Nullable<bool> fldHaveEbtal { get; set; }
        public Nullable<bool> fldHaveEtmam { get; set; }
        public string fldTitleEbtal { get; set; }
        public string fldTitleEtmam { get; set; }
    }
}
