//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_RptListCodeDaramad_Asli
    {
        public string P_DaramdCode { get; set; }
        public string P_DaramadTitle { get; set; }
        public Nullable<long> Mablagh { get; set; }
        public Nullable<int> Count { get; set; }
        public string fldTarikh { get; set; }
        public string fldShomareHesab { get; set; }
        public Nullable<int> fldShomareHesabId { get; set; }
    }
}
