//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_SelectHesabDaryaftani
    {
        public int fldSerialFish { get; set; }
        public long fldBedehkar { get; set; }
        public long fldBestankar { get; set; }
        public string fldName { get; set; }
        public string fldCode { get; set; }
        public string fldNameCoding { get; set; }
        public long fldMande { get; set; }
        public string fldNameShakhs { get; set; }
        public int fldElamAvarezId { get; set; }
        public Nullable<int> fldModuleErsalId { get; set; }
        public string fldCaseTypeName { get; set; }
    }
}
