//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    
    public partial class spr_GetUserGroupTree
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public Nullable<bool> fldGrant { get; set; }
        public Nullable<bool> fldWithGrant { get; set; }
        public int fldUserID { get; set; }
        public Nullable<bool> fldWithGrantLogin { get; set; }
    }
}
