//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_FMS.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeighEntities : DbContext
    {
        public WeighEntities()
            : base("name=WeighEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblWeighbridgeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblWeighbridgeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblWeighbridgeInsert(Nullable<int> fldAshkhasHoghoghiId, string fldName, string fldAddress, Nullable<int> fldUserId, string fldDesc, string fldIP, string fldPassword)
        {
            var fldAshkhasHoghoghiIdParameter = fldAshkhasHoghoghiId.HasValue ?
                new ObjectParameter("fldAshkhasHoghoghiId", fldAshkhasHoghoghiId) :
                new ObjectParameter("fldAshkhasHoghoghiId", typeof(int));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldPasswordParameter = fldPassword != null ?
                new ObjectParameter("fldPassword", fldPassword) :
                new ObjectParameter("fldPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblWeighbridgeInsert", fldAshkhasHoghoghiIdParameter, fldNameParameter, fldAddressParameter, fldUserIdParameter, fldDescParameter, fldIPParameter, fldPasswordParameter);
        }
    
        public virtual ObjectResult<spr_tblWeighbridgeSelect> spr_tblWeighbridgeSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblWeighbridgeSelect>("spr_tblWeighbridgeSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblWeighbridgeUpdate(Nullable<int> fldId, Nullable<int> fldAshkhasHoghoghiId, string fldName, string fldAddress, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldAshkhasHoghoghiIdParameter = fldAshkhasHoghoghiId.HasValue ?
                new ObjectParameter("fldAshkhasHoghoghiId", fldAshkhasHoghoghiId) :
                new ObjectParameter("fldAshkhasHoghoghiId", typeof(int));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblWeighbridgeUpdate", fldIdParameter, fldAshkhasHoghoghiIdParameter, fldNameParameter, fldAddressParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblRemittance_HeaderDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRemittance_HeaderDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual ObjectResult<spr_tblRemittance_HeaderSelect> spr_tblRemittance_HeaderSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblRemittance_HeaderSelect>("spr_tblRemittance_HeaderSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_SelectBaskoolParametr_Value> spr_SelectBaskoolParametr_Value(Nullable<int> baskoolId)
        {
            var baskoolIdParameter = baskoolId.HasValue ?
                new ObjectParameter("baskoolId", baskoolId) :
                new ObjectParameter("baskoolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectBaskoolParametr_Value>("spr_SelectBaskoolParametr_Value", baskoolIdParameter);
        }
    
        public virtual int spr_tblParametrBaskoolValueInsert(Nullable<int> fldParametrBaskoolId, Nullable<int> fldBaskoolId, string fldValue, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldParametrBaskoolIdParameter = fldParametrBaskoolId.HasValue ?
                new ObjectParameter("fldParametrBaskoolId", fldParametrBaskoolId) :
                new ObjectParameter("fldParametrBaskoolId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParametrBaskoolValueInsert", fldParametrBaskoolIdParameter, fldBaskoolIdParameter, fldValueParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblParametrBaskoolValueSelect> spr_tblParametrBaskoolValueSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblParametrBaskoolValueSelect>("spr_tblParametrBaskoolValueSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblParametrBaskoolValueUpdate(Nullable<int> fldId, Nullable<int> fldParametrBaskoolId, Nullable<int> fldBaskoolId, string fldValue, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldParametrBaskoolIdParameter = fldParametrBaskoolId.HasValue ?
                new ObjectParameter("fldParametrBaskoolId", fldParametrBaskoolId) :
                new ObjectParameter("fldParametrBaskoolId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParametrBaskoolValueUpdate", fldIdParameter, fldParametrBaskoolIdParameter, fldBaskoolIdParameter, fldValueParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblRemittance_DetailsSelect> spr_tblRemittance_DetailsSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblRemittance_DetailsSelect>("spr_tblRemittance_DetailsSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblParametrsBaskoolInsert(string fldEnName, string fldFaName, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldEnNameParameter = fldEnName != null ?
                new ObjectParameter("fldEnName", fldEnName) :
                new ObjectParameter("fldEnName", typeof(string));
    
            var fldFaNameParameter = fldFaName != null ?
                new ObjectParameter("fldFaName", fldFaName) :
                new ObjectParameter("fldFaName", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParametrsBaskoolInsert", fldEnNameParameter, fldFaNameParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblParametrBaskoolValueDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblParametrBaskoolValueDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual ObjectResult<spr_tblParametrsBaskoolSelect> spr_tblParametrsBaskoolSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblParametrsBaskoolSelect>("spr_tblParametrsBaskoolSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblBaskolDocumentSelect> spr_tblBaskolDocumentSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblBaskolDocumentSelect>("spr_tblBaskolDocumentSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblArzeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArzeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblArzeInsert(ObjectParameter fldID, Nullable<int> fldBaskoolId, Nullable<int> fldKalaId, Nullable<int> fldShomareHesabCodeDaramadId, Nullable<byte> fldTedad, Nullable<long> fldMablagh, Nullable<byte> fldStatusForoosh, Nullable<int> fldVaznVahed, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldKalaIdParameter = fldKalaId.HasValue ?
                new ObjectParameter("fldKalaId", fldKalaId) :
                new ObjectParameter("fldKalaId", typeof(int));
    
            var fldShomareHesabCodeDaramadIdParameter = fldShomareHesabCodeDaramadId.HasValue ?
                new ObjectParameter("fldShomareHesabCodeDaramadId", fldShomareHesabCodeDaramadId) :
                new ObjectParameter("fldShomareHesabCodeDaramadId", typeof(int));
    
            var fldTedadParameter = fldTedad.HasValue ?
                new ObjectParameter("fldTedad", fldTedad) :
                new ObjectParameter("fldTedad", typeof(byte));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldStatusForooshParameter = fldStatusForoosh.HasValue ?
                new ObjectParameter("fldStatusForoosh", fldStatusForoosh) :
                new ObjectParameter("fldStatusForoosh", typeof(byte));
    
            var fldVaznVahedParameter = fldVaznVahed.HasValue ?
                new ObjectParameter("fldVaznVahed", fldVaznVahed) :
                new ObjectParameter("fldVaznVahed", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArzeInsert", fldID, fldBaskoolIdParameter, fldKalaIdParameter, fldShomareHesabCodeDaramadIdParameter, fldTedadParameter, fldMablaghParameter, fldStatusForooshParameter, fldVaznVahedParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblArzeSelect> spr_tblArzeSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblArzeSelect>("spr_tblArzeSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblArzeUpdate(Nullable<int> fldId, Nullable<int> fldBaskoolId, Nullable<int> fldKalaId, Nullable<int> fldShomareHesabCodeDaramadId, Nullable<byte> fldTedad, Nullable<long> fldMablagh, Nullable<byte> fldStatusForoosh, Nullable<int> fldVaznVahed, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldKalaIdParameter = fldKalaId.HasValue ?
                new ObjectParameter("fldKalaId", fldKalaId) :
                new ObjectParameter("fldKalaId", typeof(int));
    
            var fldShomareHesabCodeDaramadIdParameter = fldShomareHesabCodeDaramadId.HasValue ?
                new ObjectParameter("fldShomareHesabCodeDaramadId", fldShomareHesabCodeDaramadId) :
                new ObjectParameter("fldShomareHesabCodeDaramadId", typeof(int));
    
            var fldTedadParameter = fldTedad.HasValue ?
                new ObjectParameter("fldTedad", fldTedad) :
                new ObjectParameter("fldTedad", typeof(byte));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldStatusForooshParameter = fldStatusForoosh.HasValue ?
                new ObjectParameter("fldStatusForoosh", fldStatusForoosh) :
                new ObjectParameter("fldStatusForoosh", typeof(byte));
    
            var fldVaznVahedParameter = fldVaznVahed.HasValue ?
                new ObjectParameter("fldVaznVahed", fldVaznVahed) :
                new ObjectParameter("fldVaznVahed", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArzeUpdate", fldIdParameter, fldBaskoolIdParameter, fldKalaIdParameter, fldShomareHesabCodeDaramadIdParameter, fldTedadParameter, fldMablaghParameter, fldStatusForooshParameter, fldVaznVahedParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblRemittance_HeaderInsert(Nullable<int> fldAshkhasiId, Nullable<bool> fldStatus, string fldStartDate, string fldEndDate, byte[] fldFile, string fldpasvand, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDescHeader, Nullable<int> fldEmployId, Nullable<int> fldChartOrganEjraeeId, string fldIP, string fldTitle)
        {
            var fldAshkhasiIdParameter = fldAshkhasiId.HasValue ?
                new ObjectParameter("fldAshkhasiId", fldAshkhasiId) :
                new ObjectParameter("fldAshkhasiId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldStartDateParameter = fldStartDate != null ?
                new ObjectParameter("fldStartDate", fldStartDate) :
                new ObjectParameter("fldStartDate", typeof(string));
    
            var fldEndDateParameter = fldEndDate != null ?
                new ObjectParameter("fldEndDate", fldEndDate) :
                new ObjectParameter("fldEndDate", typeof(string));
    
            var fldFileParameter = fldFile != null ?
                new ObjectParameter("fldFile", fldFile) :
                new ObjectParameter("fldFile", typeof(byte[]));
    
            var fldpasvandParameter = fldpasvand != null ?
                new ObjectParameter("fldpasvand", fldpasvand) :
                new ObjectParameter("fldpasvand", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescHeaderParameter = fldDescHeader != null ?
                new ObjectParameter("fldDescHeader", fldDescHeader) :
                new ObjectParameter("fldDescHeader", typeof(string));
    
            var fldEmployIdParameter = fldEmployId.HasValue ?
                new ObjectParameter("fldEmployId", fldEmployId) :
                new ObjectParameter("fldEmployId", typeof(int));
    
            var fldChartOrganEjraeeIdParameter = fldChartOrganEjraeeId.HasValue ?
                new ObjectParameter("fldChartOrganEjraeeId", fldChartOrganEjraeeId) :
                new ObjectParameter("fldChartOrganEjraeeId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRemittance_HeaderInsert", fldAshkhasiIdParameter, fldStatusParameter, fldStartDateParameter, fldEndDateParameter, fldFileParameter, fldpasvandParameter, fldUserIdParameter, fldOrganIdParameter, fldDescHeaderParameter, fldEmployIdParameter, fldChartOrganEjraeeIdParameter, fldIPParameter, fldTitleParameter);
        }
    
        public virtual int spr_tblRemittance_HeaderUpdate(Nullable<int> fldHeaderId, Nullable<int> fldAshkhasiId, Nullable<bool> fldStatus, string fldStartDate, string fldEndDate, Nullable<int> fldFileId, byte[] fldFile, string fldpasvand, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDescHeader, Nullable<int> fldEmployId, Nullable<int> fldChartOrganEjraeeId, string fldIP, string fldTitle)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(int));
    
            var fldAshkhasiIdParameter = fldAshkhasiId.HasValue ?
                new ObjectParameter("fldAshkhasiId", fldAshkhasiId) :
                new ObjectParameter("fldAshkhasiId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldStartDateParameter = fldStartDate != null ?
                new ObjectParameter("fldStartDate", fldStartDate) :
                new ObjectParameter("fldStartDate", typeof(string));
    
            var fldEndDateParameter = fldEndDate != null ?
                new ObjectParameter("fldEndDate", fldEndDate) :
                new ObjectParameter("fldEndDate", typeof(string));
    
            var fldFileIdParameter = fldFileId.HasValue ?
                new ObjectParameter("fldFileId", fldFileId) :
                new ObjectParameter("fldFileId", typeof(int));
    
            var fldFileParameter = fldFile != null ?
                new ObjectParameter("fldFile", fldFile) :
                new ObjectParameter("fldFile", typeof(byte[]));
    
            var fldpasvandParameter = fldpasvand != null ?
                new ObjectParameter("fldpasvand", fldpasvand) :
                new ObjectParameter("fldpasvand", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescHeaderParameter = fldDescHeader != null ?
                new ObjectParameter("fldDescHeader", fldDescHeader) :
                new ObjectParameter("fldDescHeader", typeof(string));
    
            var fldEmployIdParameter = fldEmployId.HasValue ?
                new ObjectParameter("fldEmployId", fldEmployId) :
                new ObjectParameter("fldEmployId", typeof(int));
    
            var fldChartOrganEjraeeIdParameter = fldChartOrganEjraeeId.HasValue ?
                new ObjectParameter("fldChartOrganEjraeeId", fldChartOrganEjraeeId) :
                new ObjectParameter("fldChartOrganEjraeeId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblRemittance_HeaderUpdate", fldHeaderIdParameter, fldAshkhasiIdParameter, fldStatusParameter, fldStartDateParameter, fldEndDateParameter, fldFileIdParameter, fldFileParameter, fldpasvandParameter, fldUserIdParameter, fldOrganIdParameter, fldDescHeaderParameter, fldEmployIdParameter, fldChartOrganEjraeeIdParameter, fldIPParameter, fldTitleParameter);
        }
    
        public virtual ObjectResult<spr_SelectArze_Kala> spr_SelectArze_Kala(Nullable<int> fldBaskoolId, Nullable<int> fldOrganId)
        {
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectArze_Kala>("spr_SelectArze_Kala", fldBaskoolIdParameter, fldOrganIdParameter);
        }
    
        public virtual int spr_UpdatePassBaskool(Nullable<int> fldid, string pass, Nullable<int> userId)
        {
            var fldidParameter = fldid.HasValue ?
                new ObjectParameter("fldid", fldid) :
                new ObjectParameter("fldid", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdatePassBaskool", fldidParameter, passParameter, userIdParameter);
        }
    
        public virtual int spr_tblLoadingPlaceDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLoadingPlaceDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblLoadingPlaceInsert(string fldName, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLoadingPlaceInsert", fldNameParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblLoadingPlaceSelect> spr_tblLoadingPlaceSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLoadingPlaceSelect>("spr_tblLoadingPlaceSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblLoadingPlaceUpdate(Nullable<int> fldId, string fldName, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLoadingPlaceUpdate", fldIdParameter, fldNameParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblArze_DetailSelect> spr_tblArze_DetailSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblArze_DetailSelect>("spr_tblArze_DetailSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblNoeMasrafSelect> spr_tblNoeMasrafSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblNoeMasrafSelect>("spr_tblNoeMasrafSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblArze_DetailDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArze_DetailDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblArze_DetailInsert(Nullable<int> fldHeaderId, Nullable<int> fldParametrSabetCodeDaramd, string fldValue, Nullable<bool> fldFlag, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(int));
    
            var fldParametrSabetCodeDaramdParameter = fldParametrSabetCodeDaramd.HasValue ?
                new ObjectParameter("fldParametrSabetCodeDaramd", fldParametrSabetCodeDaramd) :
                new ObjectParameter("fldParametrSabetCodeDaramd", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldFlagParameter = fldFlag.HasValue ?
                new ObjectParameter("fldFlag", fldFlag) :
                new ObjectParameter("fldFlag", typeof(bool));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblArze_DetailInsert", fldHeaderIdParameter, fldParametrSabetCodeDaramdParameter, fldValueParameter, fldFlagParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblVazn_BaskoolInsert(ObjectParameter fldID, string haraf, string plaque1, string plaque2, Nullable<byte> serial, Nullable<int> fldRananadeId, Nullable<byte> fldNoeMasrafId, Nullable<int> fldAshkhasId, Nullable<int> fldChartOrganEjraeeId, Nullable<int> fldLoadingPlaceId, Nullable<int> fldKalaId, Nullable<decimal> fldVaznKol, Nullable<int> fldRemittanceId, Nullable<int> fldBaskoolId, Nullable<bool> fldIsPor, Nullable<int> fldTypeKhodroId, Nullable<int> fldTedad, Nullable<bool> fldTypeMohasebe, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var harafParameter = haraf != null ?
                new ObjectParameter("Haraf", haraf) :
                new ObjectParameter("Haraf", typeof(string));
    
            var plaque1Parameter = plaque1 != null ?
                new ObjectParameter("Plaque1", plaque1) :
                new ObjectParameter("Plaque1", typeof(string));
    
            var plaque2Parameter = plaque2 != null ?
                new ObjectParameter("Plaque2", plaque2) :
                new ObjectParameter("Plaque2", typeof(string));
    
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(byte));
    
            var fldRananadeIdParameter = fldRananadeId.HasValue ?
                new ObjectParameter("fldRananadeId", fldRananadeId) :
                new ObjectParameter("fldRananadeId", typeof(int));
    
            var fldNoeMasrafIdParameter = fldNoeMasrafId.HasValue ?
                new ObjectParameter("fldNoeMasrafId", fldNoeMasrafId) :
                new ObjectParameter("fldNoeMasrafId", typeof(byte));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldChartOrganEjraeeIdParameter = fldChartOrganEjraeeId.HasValue ?
                new ObjectParameter("fldChartOrganEjraeeId", fldChartOrganEjraeeId) :
                new ObjectParameter("fldChartOrganEjraeeId", typeof(int));
    
            var fldLoadingPlaceIdParameter = fldLoadingPlaceId.HasValue ?
                new ObjectParameter("fldLoadingPlaceId", fldLoadingPlaceId) :
                new ObjectParameter("fldLoadingPlaceId", typeof(int));
    
            var fldKalaIdParameter = fldKalaId.HasValue ?
                new ObjectParameter("fldKalaId", fldKalaId) :
                new ObjectParameter("fldKalaId", typeof(int));
    
            var fldVaznKolParameter = fldVaznKol.HasValue ?
                new ObjectParameter("fldVaznKol", fldVaznKol) :
                new ObjectParameter("fldVaznKol", typeof(decimal));
    
            var fldRemittanceIdParameter = fldRemittanceId.HasValue ?
                new ObjectParameter("fldRemittanceId", fldRemittanceId) :
                new ObjectParameter("fldRemittanceId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldIsPorParameter = fldIsPor.HasValue ?
                new ObjectParameter("fldIsPor", fldIsPor) :
                new ObjectParameter("fldIsPor", typeof(bool));
    
            var fldTypeKhodroIdParameter = fldTypeKhodroId.HasValue ?
                new ObjectParameter("fldTypeKhodroId", fldTypeKhodroId) :
                new ObjectParameter("fldTypeKhodroId", typeof(int));
    
            var fldTedadParameter = fldTedad.HasValue ?
                new ObjectParameter("fldTedad", fldTedad) :
                new ObjectParameter("fldTedad", typeof(int));
    
            var fldTypeMohasebeParameter = fldTypeMohasebe.HasValue ?
                new ObjectParameter("fldTypeMohasebe", fldTypeMohasebe) :
                new ObjectParameter("fldTypeMohasebe", typeof(bool));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblVazn_BaskoolInsert", fldID, harafParameter, plaque1Parameter, plaque2Parameter, serialParameter, fldRananadeIdParameter, fldNoeMasrafIdParameter, fldAshkhasIdParameter, fldChartOrganEjraeeIdParameter, fldLoadingPlaceIdParameter, fldKalaIdParameter, fldVaznKolParameter, fldRemittanceIdParameter, fldBaskoolIdParameter, fldIsPorParameter, fldTypeKhodroIdParameter, fldTedadParameter, fldTypeMohasebeParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblVazn_BaskoolSelect> spr_tblVazn_BaskoolSelect(string fieldName, string value, Nullable<int> moduleId, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(int));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblVazn_BaskoolSelect>("spr_tblVazn_BaskoolSelect", fieldNameParameter, valueParameter, moduleIdParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_SelectRannadeInPlaque> spr_SelectRannadeInPlaque(string fieldName, Nullable<byte> fldSerialPlaque, string haraf, string plaque1, string plaque2, Nullable<int> baskoolId, Nullable<int> organId)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("fieldName", fieldName) :
                new ObjectParameter("fieldName", typeof(string));
    
            var fldSerialPlaqueParameter = fldSerialPlaque.HasValue ?
                new ObjectParameter("fldSerialPlaque", fldSerialPlaque) :
                new ObjectParameter("fldSerialPlaque", typeof(byte));
    
            var harafParameter = haraf != null ?
                new ObjectParameter("Haraf", haraf) :
                new ObjectParameter("Haraf", typeof(string));
    
            var plaque1Parameter = plaque1 != null ?
                new ObjectParameter("Plaque1", plaque1) :
                new ObjectParameter("Plaque1", typeof(string));
    
            var plaque2Parameter = plaque2 != null ?
                new ObjectParameter("Plaque2", plaque2) :
                new ObjectParameter("Plaque2", typeof(string));
    
            var baskoolIdParameter = baskoolId.HasValue ?
                new ObjectParameter("BaskoolId", baskoolId) :
                new ObjectParameter("BaskoolId", typeof(int));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectRannadeInPlaque>("spr_SelectRannadeInPlaque", fieldNameParameter, fldSerialPlaqueParameter, harafParameter, plaque1Parameter, plaque2Parameter, baskoolIdParameter, organIdParameter);
        }
    
        public virtual ObjectResult<spr_SelectMandeHavali> spr_SelectMandeHavali(Nullable<int> idHavale, Nullable<int> idBaskool, Nullable<int> idKala)
        {
            var idHavaleParameter = idHavale.HasValue ?
                new ObjectParameter("IdHavale", idHavale) :
                new ObjectParameter("IdHavale", typeof(int));
    
            var idBaskoolParameter = idBaskool.HasValue ?
                new ObjectParameter("IdBaskool", idBaskool) :
                new ObjectParameter("IdBaskool", typeof(int));
    
            var idKalaParameter = idKala.HasValue ?
                new ObjectParameter("IdKala", idKala) :
                new ObjectParameter("IdKala", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectMandeHavali>("spr_SelectMandeHavali", idHavaleParameter, idBaskoolParameter, idKalaParameter);
        }
    
        public virtual ObjectResult<spr_SelectVaznKhals_VaznKhali> spr_SelectVaznKhals_VaznKhali(string haraf, string plaque1, string plaque2, Nullable<byte> serial, Nullable<int> fldBaskoolId, Nullable<int> organId, Nullable<decimal> vaznKol, Nullable<bool> type)
        {
            var harafParameter = haraf != null ?
                new ObjectParameter("Haraf", haraf) :
                new ObjectParameter("Haraf", typeof(string));
    
            var plaque1Parameter = plaque1 != null ?
                new ObjectParameter("Plaque1", plaque1) :
                new ObjectParameter("Plaque1", typeof(string));
    
            var plaque2Parameter = plaque2 != null ?
                new ObjectParameter("Plaque2", plaque2) :
                new ObjectParameter("Plaque2", typeof(string));
    
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(byte));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var vaznKolParameter = vaznKol.HasValue ?
                new ObjectParameter("vaznKol", vaznKol) :
                new ObjectParameter("vaznKol", typeof(decimal));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectVaznKhals_VaznKhali>("spr_SelectVaznKhals_VaznKhali", harafParameter, plaque1Parameter, plaque2Parameter, serialParameter, fldBaskoolIdParameter, organIdParameter, vaznKolParameter, typeParameter);
        }
    
        public virtual int spr_tblVazn_BaskoolUpdate(Nullable<int> fldId, Nullable<int> fldPluqeId, Nullable<int> fldRananadeId, Nullable<byte> fldNoeMasrafId, Nullable<int> fldAshkhasId, Nullable<int> fldChartOrganEjraeeId, Nullable<int> fldLoadingPlaceId, Nullable<int> fldKalaId, Nullable<decimal> fldVaznKol, Nullable<int> fldRemittanceId, Nullable<int> fldBaskoolId, Nullable<bool> fldIsPor, Nullable<int> fldTypeKhodroId, Nullable<int> fldTedad, Nullable<bool> fldTypeMohasebe, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldPluqeIdParameter = fldPluqeId.HasValue ?
                new ObjectParameter("fldPluqeId", fldPluqeId) :
                new ObjectParameter("fldPluqeId", typeof(int));
    
            var fldRananadeIdParameter = fldRananadeId.HasValue ?
                new ObjectParameter("fldRananadeId", fldRananadeId) :
                new ObjectParameter("fldRananadeId", typeof(int));
    
            var fldNoeMasrafIdParameter = fldNoeMasrafId.HasValue ?
                new ObjectParameter("fldNoeMasrafId", fldNoeMasrafId) :
                new ObjectParameter("fldNoeMasrafId", typeof(byte));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldChartOrganEjraeeIdParameter = fldChartOrganEjraeeId.HasValue ?
                new ObjectParameter("fldChartOrganEjraeeId", fldChartOrganEjraeeId) :
                new ObjectParameter("fldChartOrganEjraeeId", typeof(int));
    
            var fldLoadingPlaceIdParameter = fldLoadingPlaceId.HasValue ?
                new ObjectParameter("fldLoadingPlaceId", fldLoadingPlaceId) :
                new ObjectParameter("fldLoadingPlaceId", typeof(int));
    
            var fldKalaIdParameter = fldKalaId.HasValue ?
                new ObjectParameter("fldKalaId", fldKalaId) :
                new ObjectParameter("fldKalaId", typeof(int));
    
            var fldVaznKolParameter = fldVaznKol.HasValue ?
                new ObjectParameter("fldVaznKol", fldVaznKol) :
                new ObjectParameter("fldVaznKol", typeof(decimal));
    
            var fldRemittanceIdParameter = fldRemittanceId.HasValue ?
                new ObjectParameter("fldRemittanceId", fldRemittanceId) :
                new ObjectParameter("fldRemittanceId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldIsPorParameter = fldIsPor.HasValue ?
                new ObjectParameter("fldIsPor", fldIsPor) :
                new ObjectParameter("fldIsPor", typeof(bool));
    
            var fldTypeKhodroIdParameter = fldTypeKhodroId.HasValue ?
                new ObjectParameter("fldTypeKhodroId", fldTypeKhodroId) :
                new ObjectParameter("fldTypeKhodroId", typeof(int));
    
            var fldTedadParameter = fldTedad.HasValue ?
                new ObjectParameter("fldTedad", fldTedad) :
                new ObjectParameter("fldTedad", typeof(int));
    
            var fldTypeMohasebeParameter = fldTypeMohasebe.HasValue ?
                new ObjectParameter("fldTypeMohasebe", fldTypeMohasebe) :
                new ObjectParameter("fldTypeMohasebe", typeof(bool));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblVazn_BaskoolUpdate", fldIdParameter, fldPluqeIdParameter, fldRananadeIdParameter, fldNoeMasrafIdParameter, fldAshkhasIdParameter, fldChartOrganEjraeeIdParameter, fldLoadingPlaceIdParameter, fldKalaIdParameter, fldVaznKolParameter, fldRemittanceIdParameter, fldBaskoolIdParameter, fldIsPorParameter, fldTypeKhodroIdParameter, fldTedadParameter, fldTypeMohasebeParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblTozinInsert(Nullable<int> fldWeighbridgeId, Nullable<int> fldMaxW, Nullable<int> fldPlaqueId, Nullable<System.DateTime> fldHour, Nullable<System.DateTime> fldStartDate, Nullable<System.DateTime> fldEndDate)
        {
            var fldWeighbridgeIdParameter = fldWeighbridgeId.HasValue ?
                new ObjectParameter("fldWeighbridgeId", fldWeighbridgeId) :
                new ObjectParameter("fldWeighbridgeId", typeof(int));
    
            var fldMaxWParameter = fldMaxW.HasValue ?
                new ObjectParameter("fldMaxW", fldMaxW) :
                new ObjectParameter("fldMaxW", typeof(int));
    
            var fldPlaqueIdParameter = fldPlaqueId.HasValue ?
                new ObjectParameter("fldPlaqueId", fldPlaqueId) :
                new ObjectParameter("fldPlaqueId", typeof(int));
    
            var fldHourParameter = fldHour.HasValue ?
                new ObjectParameter("fldHour", fldHour) :
                new ObjectParameter("fldHour", typeof(System.DateTime));
    
            var fldStartDateParameter = fldStartDate.HasValue ?
                new ObjectParameter("fldStartDate", fldStartDate) :
                new ObjectParameter("fldStartDate", typeof(System.DateTime));
    
            var fldEndDateParameter = fldEndDate.HasValue ?
                new ObjectParameter("fldEndDate", fldEndDate) :
                new ObjectParameter("fldEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTozinInsert", fldWeighbridgeIdParameter, fldMaxWParameter, fldPlaqueIdParameter, fldHourParameter, fldStartDateParameter, fldEndDateParameter);
        }
    
        public virtual ObjectResult<spr_tblTozinSelect> spr_tblTozinSelect(string fieldName, string value, string value2, string aztarikh, string tatarikh, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("Value2", value2) :
                new ObjectParameter("Value2", typeof(string));
    
            var aztarikhParameter = aztarikh != null ?
                new ObjectParameter("Aztarikh", aztarikh) :
                new ObjectParameter("Aztarikh", typeof(string));
    
            var tatarikhParameter = tatarikh != null ?
                new ObjectParameter("Tatarikh", tatarikh) :
                new ObjectParameter("Tatarikh", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTozinSelect>("spr_tblTozinSelect", fieldNameParameter, valueParameter, value2Parameter, aztarikhParameter, tatarikhParameter, hParameter);
        }
    
        public virtual int spr_UpdateIsprintBaskool(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateIsprintBaskool", idParameter);
        }
    
        public virtual int spr_UpdateEbtalBaskool(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateEbtalBaskool", idParameter);
        }
    
        public virtual int spr_tblTypeReportInsert(Nullable<byte> fldType, Nullable<int> fldOrganId, Nullable<int> fldBaskoolId, Nullable<int> fldUserId, string fldIP)
        {
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(byte));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldBaskoolIdParameter = fldBaskoolId.HasValue ?
                new ObjectParameter("fldBaskoolId", fldBaskoolId) :
                new ObjectParameter("fldBaskoolId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTypeReportInsert", fldTypeParameter, fldOrganIdParameter, fldBaskoolIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblTypeReportSelect> spr_tblTypeReportSelect(string fieldName, string value, string value2, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("Value2", value2) :
                new ObjectParameter("Value2", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTypeReportSelect>("spr_tblTypeReportSelect", fieldNameParameter, valueParameter, value2Parameter, hParameter);
        }
    
        public virtual ObjectResult<spr_SelectSumKalaHavale> spr_SelectSumKalaHavale(string fieldName, string value, Nullable<int> idHavale)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("fieldName", fieldName) :
                new ObjectParameter("fieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var idHavaleParameter = idHavale.HasValue ?
                new ObjectParameter("idHavale", idHavale) :
                new ObjectParameter("idHavale", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectSumKalaHavale>("spr_SelectSumKalaHavale", fieldNameParameter, valueParameter, idHavaleParameter);
        }
    
        public virtual ObjectResult<spr_SelectSumKalaHavale_Detail> spr_SelectSumKalaHavale_Detail(string fieldname, string value, Nullable<int> idHavale, Nullable<int> idKala)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var idHavaleParameter = idHavale.HasValue ?
                new ObjectParameter("idHavale", idHavale) :
                new ObjectParameter("idHavale", typeof(int));
    
            var idKalaParameter = idKala.HasValue ?
                new ObjectParameter("idKala", idKala) :
                new ObjectParameter("idKala", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectSumKalaHavale_Detail>("spr_SelectSumKalaHavale_Detail", fieldnameParameter, valueParameter, idHavaleParameter, idKalaParameter);
        }
    
        public virtual int spr_tblElamAvarez_ModuleOrganInsert(Nullable<int> fldElamAvarezId, Nullable<int> fldCodeDaramdElamAvarezId, Nullable<int> id, Nullable<int> fldUserId, string fldIP, string fldDesc)
        {
            var fldElamAvarezIdParameter = fldElamAvarezId.HasValue ?
                new ObjectParameter("fldElamAvarezId", fldElamAvarezId) :
                new ObjectParameter("fldElamAvarezId", typeof(int));
    
            var fldCodeDaramdElamAvarezIdParameter = fldCodeDaramdElamAvarezId.HasValue ?
                new ObjectParameter("fldCodeDaramdElamAvarezId", fldCodeDaramdElamAvarezId) :
                new ObjectParameter("fldCodeDaramdElamAvarezId", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblElamAvarez_ModuleOrganInsert", fldElamAvarezIdParameter, fldCodeDaramdElamAvarezIdParameter, idParameter, fldUserIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblElamAvarez_ModuleOrganSelect> spr_tblElamAvarez_ModuleOrganSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblElamAvarez_ModuleOrganSelect>("spr_tblElamAvarez_ModuleOrganSelect", fieldNameParameter, valueParameter, hParameter);
        }
    }
}
