
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCF_FMS.DAL.Model;
using WCF_FMS.TOL.PayRoll;

namespace WCF_FMS.DAL.PayRoll
{
    public class DL_DisketBazneshastegi
    {
        #region Select
        public List<OBJ_DisketBazneshastegi> Select(short Year, byte Mah, byte Nobat,int OrganId)
        {
            using (RasaFMSPayRollDBEntities p = new RasaFMSPayRollDBEntities())
            {
                var k = p.spr_Pay_DisketBazneshastegi(Year, Mah, Nobat, OrganId)
                    .Select(q => new OBJ_DisketBazneshastegi()
                    {
                        fldName=q.fldName,
                        fldFamily=q.fldFamily,
                        fldJensiyat=q.fldJensiyat,
                        fldFatherName=q.fldFatherName,
                        fldCodemeli=q.fldCodemeli,
                        fldSh_Shenasname=q.fldSh_Shenasname,
                        StateNameSodoor=q.StateNameSodoor,
                        CityNameSodoor=q.CityNameSodoor,
                        fldTarikhTavalod=q.fldTarikhTavalod,
                        fldSh_Personali=q.fldSh_Personali,
                        TitleMadrak=q.fldMadrakTahsili,
                        TitleReshte=q.TitleReshte,
                        TitleNezamVazife = q.fldNezamVazifeTitle,
                        fldRasteShoghli=q.fldRasteShoghli,
                        OrganPost=q.OrganPost,
                        fldReshteShoghli=q.fldReshteShoghli,
                        fldTabaghe=q.fldTabaghe,
                        fldGroup=(byte)q.fldGroup,
                        fldStatusTaaholName=q.fldTaaholBazneshastegi,
                        fldTedadFarzand=(byte)q.fldTedadFarzand,
                        fldTypeEstekhdam=q.fldTypeEstekhdamBaz,
                        fldModeEstekhdam=q.fldHalateEstekhdam,
                        fldTarikhEstekhdam=q.fldTarikhEstekhdam,
                        fldEsargariName=q.fldEsarBazneshastegi,
                        fldNesbat=q.fldNesbatBaz,
                        FundChangeDate="0",
                        fldSanavatRasmi = q.s_rasmi,
                        fldSanavatGheyrRasmi=q.s_gheyrerasmi,
                        fldKarkard=q.fldKarkard,
                        fldTarikhMoafiat=q.fldTarikhMazad30Sal,
                        fldTarikhEjra=q.fldTarikhEjra,
                        fldTypeHokm=q.fldTypeHokm,
                        fldMobile=q.fldMobile,
                        h_paye=q.h_paye,
                        sanavat=q.sanavat,
                        foghshoghl=q.foghshoghl,
                        jazb=(int)q.jazb,
                        vije = (int)q.vije,
                        talash=q.talash,
                        xRay=0,
                        barjastegi=q.barjastegi,
                        modiryati=q.modiryati,
                        takhasosi=q.takhasosi,
                        sakhtikar=q.sakhtikar,
                        nobatkari=q.nobatkari,
                        tatbigh=q.tatbigh,
                        hadaghaltadil=q.hadaghaltadil,
                        Bahrevari=q.riali,
                        hamtarazi=q.sanavat_isar+q.fogh_isar+q.made26,
                        tadil=q.tadil,
                        band_y=(int)q.band_y,
                        Tanazol=0,
                        tatbigh1=q.tatbigh1,
                        Kahesh=0,
                        Tarmim=q.tarmim,
                        fldExExpert=q.fldExExpert,
                        fldMashmolBime=q.fldMashmolBime,
                        fldBimePersonal=q.fldBimePersonal,
                        fldBimeKarFarma=q.fldBimeKarFarma,
                        fldMashmolBimeMoavaghe=q.fldMashmolBimeMoavaghe,
                        fldBimePersonalMoavaghe=q.fldBimePersonalMoavaghe,
                        fldBimeKarfarmaMoavaghe=q.fldBimeKarfarmaMoavaghe,
                        fldMashmoolKosour=0,
                        fldPersonalMashmoolKosour=0,
                        fldKarfarmaMashmoolKosour=0,
                        fldMogharari=q.fldMogharari,
                        fldMazad30Sal=q.fldMazad30Sal,
                        Installments=0,
                        MoafiatZood=0,
                        EnteghalBime=0,
                        TotalKosour=(int)q.jame,
                        made26=q.made26,
                        ghazai=q.ghazai,
                        jazbTakhasosi=q.jazbTakhasosi,
                        jazbtadil=q.jazbtadil,
                        riali=0,
                        jebhe=q.jebhe,
                        fldStatusTaaholId=q.fldStatusTaaholId,
                        fldNezamVazifeId=q.fldNezamVazifeId,
                        fldMadrakId=q.fldMadrakId,
                        fldEsargariId=q.fldEsargariId,
                        fldMoreGroup=q.fldMoreGroup,
                        sanavat_isar=0,
                        fogh_isar=0,
                       zaribtadil= q.zaribtadil,
                       fldPersonalId=q.fldPersonalId
                        //barjastegi = q.barjastegi,
                        //fldBimeKarFarma = q.fldBimeKarFarma,
                        //fldBimeKarfarmaMoavaghe = q.fldBimeKarfarmaMoavaghe,
                        //fldBimePersonal = q.fldBimePersonal,
                        //fldBimePersonalMoavaghe = q.fldBimePersonalMoavaghe,
                        //fldCodemeli = q.fldCodemeli,
                        //fldFamily = q.fldFamily,
                        //fldFatherName = q.fldFatherName,
                        //fldGroup =(byte) q.fldGroup,
                        //fldJensiyat = q.fldJensiyat.ToString(),
                        //fldMashmolBime = q.fldMashmolBime,
                        //fldMashmolBimeMoavaghe = q.fldMashmolBimeMoavaghe,
                        //fldMazad30Sal = q.fldMazad30Sal,
                        //fldMogharari = q.fldMogharari,
                        //fldName = q.fldName,
                        //fldRasteShoghli = q.fldRasteShoghli,
                        //fldReshteShoghli = q.fldReshteShoghli,
                        //fldSh_Personali = q.fldSh_Personali,
                        //fldSh_Shenasname = q.fldSh_Shenasname,
                        //fldTabaghe = q.fldTabaghe,
                        //fldTarikhEjra = q.fldTarikhEjra,
                        //fldTarikhEstekhdam = q.fldTarikhEstekhdam,
                        //fldTarikhTavalod = q.fldTarikhTavalod,
                        //fldTedadFarzand = (byte)q.fldTedadFarzand,
                        //fldTypeHokm = q.fldTypeHokm,
                        //foghshoghl = q.foghshoghl,
                        //h_paye = q.h_paye,
                        //jazb = (int)q.jazb,
                        //modiryati = q.modiryati,
                        //nobatkari = q.nobatkari,
                        //OrganPost = q.OrganPost,
                        //sakhtikar = q.sakhtikar,
                        //sanavat = q.sanavat,
                        //tadil = q.tadil,
                        //takhasosi = q.takhasosi,
                        //talash = q.talash,
                        //tatbigh = q.tatbigh,
                        //TitleReshte = q.TitleReshte,
                        //vije = (int)q.vije,
                        //hadaghaltadil = q.hadaghaltadil,
                        //CityNameSodoor = q.CityNameSodoor,
                        //band_y = (int)q.band_y,
                        //tatbigh1 = q.tatbigh1,
                        //Bahrevari=0,
                        //EnteghalBime=0,
                        //fldEsargariName="",
                        //fldKarfarmaMashmoolKosour=0,
                        //fldMashmoolKosour=0,
                        //fldMobile="",
                        //fldModeEstekhdam="",
                        //fldNesbat="",
                        //fldPersonalMashmoolKosour=0,
                        //fldSanavatGheyrRasmi="",
                        //fldSanavatRasmi="",
                        //fldStatusTaaholName="",
                        //fldTarikhMoafiat="",
                        //fldTypeEstekhdam="",
                        //FundChangeDate="",
                        //hamtarazi=0,
                        //Installments=0,
                        //Kahesh=0,
                        //MoafiatZood=0,
                        //StateNameSodoor="",
                        //Tanazol=0,
                        //Tarmim=0,
                        //TitleMadrak="",
                        //TitleNezamVazife="",
                        //TotalKosour=0,
                        //xRay=0
                    }).ToList();
                return k;
            }
        }
        #endregion
    }





}